Обновление века ч1
htmlacademy-ecmascript/2073335-big-trip-simple-19 pull request #11
Opened 2023-01-19 09:04 UTC by Domish4

2023-01-19 10:43 UTC, AlexMasterov requested changes

2023-01-19 10:43 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    pointPresenter.init(pointData, this.#destinationModel);
pointPresenter.init(pointData, `this.#destinationModel`);

🤔

<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/presenter/point-list-presenter.js#L66-L70
</details>

<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/presenter/point-presenter.js#L26-L31
</details>

`tripDestinations`: `this.#destinationModel`

Модель `destinationModel` уже передана в конструктор `PointPresenter`, как его зависимость. Но название модели как массива `tripDestinations` снова путает.

2023-01-19 10:43 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    this.#sortPoints(this.#currentSortType);
При вызове методов в таком порядке массив с данными точек маршрута будет отсортирован _после_ первой отрисовки (= `this.#renderList()`), т.е. в первый раз данные будут отображаться в том порядке, в котором пришли с сервера (и находятся в модели). 

Порядок данных с сервера (и в модели) может отличаться от актуального типа сортировки, что может привести к неправильному отображению и расхождению с ТЗ.

2023-01-19 10:43 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      destinations: this.#tripDestinations
`destinations`: `this.#tripDestinations`

Сейчас `this.#tripDestinations` указывает на модель с данными, а не массив. Таким образом здесь во вью, под ложным названием, передается модель, что нарушает MVP, тема по которой является _основной_ на интенсиве.

С моделью следует работать в презентера, а во вью передавать данные (или работать с моделью через другие абстракции, вроде сервисов, view-model и т.п.).

<details>
<summary>Пример интерфейса сервиса</summary>

Для удобной работы с моделями в презентерах (и даже во вью) можешь попробовать создать _сервис_:
```js
class PointService {
  #offersModel = null;
  #destinationsModel = null;

  constructor({ offersModel, destinationsModel }) {
    this.#offersModel = offersModel;
    this.#destinationsModel = destinationsModel;
  }

  getDestinationNames() { ... }
  findDestinationById() { ... }
  findDestinationByName() { ... }

  // ...
}
```
</details>

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.element.querySelector('.event__available-offers').addEventListener('input', this.#offerChangeHandler);
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L162-L166
</details>

**5x** `this.element`.*

В методе чтобы получить элемент вью геттер [`this.element`](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/framework/view/abstract-view.js#L30-L36) вызывается повторно 5 раз, что неэффективно и усложняет чтение кода.

Можно получить элемент _один_ раз, используя переменную, и дальше в методе работать с ней.

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.element.querySelector('.event__available-offers').addEventListener('input', this.#offerChangeHandler);
.addEventListener(`'input'`, this.#offer`Change`Handler)

Д4
> Название обработчика строится следующим образом:

> (на каком элементе) + **что случилось** + Handler:

> См. также https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081018572

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +export default class EditFormView extends AbstractStatefulView {
Нужно проверить весь класс на критерий.

[Д8](https://up.htmlacademy.ru/ecmascript/19/criteries#d8)
> Методы внутри классов упорядочены

```
3. Основные методы класса
4. Обработчики событий [DOM]
5. Статические методы
```

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        destination: ''
destination: `''`

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054483407
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054483695
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1055703909

`destination` в данных (и `this._state`) указывал на _число_, а здесь ему задается пустая _строка_.

Подобная смена типа у объекта нежелательна — это негативно влияет на представление значений в памяти (теперь движку нужно учитывать, что свойство может указывать на значения разных типов), а сам подход с сменой типов далее усложнит типизацию данных с TS.

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    if (!evt.target.value) {
if (`!evt.target.value`) {

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1051289218.

Повторю, что проверки с неявным приведением типов нежелательны, _особенно для начинающих_.

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    if (evt.target.tagName === 'INPUT') {
Не понимаю, зачем здесь нужна подобная проверка.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L164

Событие `change` срабатывает при изменении `checked` у поля `input`, т.е. `evt.target` объекта события будет указывать на элемент поля `input` с (актуальным) `checked`.

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    if (evt.target.tagName === 'INPUT') {
Еще одна странная проверка на название тега.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L166

Предположу, что причина в неправильном выборе типа события:

addEventListener(`'input'`, this.#offerChangeHandler);

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  };
reset = (point) `=>` {

Здесь лучше без стрелки, чтобы метод стал частью прототипа и не создавался для каждого экземпляра класса (объекта).

Д5
> В проекте могут применяться функции, объявленные декларативно, так и стрелочные функции. **Выбранный вариант применяется к месту.** Например, по умолчанию используется декларативное объявление функций, а стрелочные функции применяются в качестве обработчиков событий, чтобы не терять контекст. Или наоборот, везде применяются стрелочные функции, а там где необходимо функции объявляются декларативно

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  static parsePointToState = (point) => ({ ...point });
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L29-L30
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L54
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L101
</details>

Не смотря на использования `AbstractStatefulView `_вся_ логика получения данных осталась в функции создания разметки шаблона.

<details>
<summary>Принцип единственной ответственности</summary>

![image](https://user-images.githubusercontent.com/700213/210588973-a91a7160-1381-40d4-b485-14576d70ae87.png)

</details>

Сейчас у функции `createTemplate` минимум две независимых причины для изменения: разметка и структуры данных (включая работу с ними).

<details>
<summary>Пример того, что ожидалась</summary>

```js
static parsePointToState = (point) => ({ 
  ...point,
  isEdit: Object.hasOwn(point, 'id'),
  destinationNames: // ...
  destinationInfo: // ...
  // ...
});
```
</details>

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L31
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L34
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L79
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L122
</details>

От доп. проверок с `?.` можно избавиться. См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/5#discussion_r1059070130.

Наличие подобных проверок указывает, что внутри приложения используются непроверенные (сырые) входные данные. Из-за этого все части приложения, все функции должны предполагать, что может быть нарушена целостность основных структур, каких-то полей может не быть, могут быть неправильные типы и т.п. 

<details>
<summary>Парсинг наугад</summary>

Специалисты в области теоретико-языковой безопасности называют эту печальную ситуацию _парсингом наугад_:

> Парсинг наугад — это [антипаттерн](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D1%82%D0%B8%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD), в котором код, выполняющий парсинг и валидацию, перемешан с бизнес логикой; Разработчики пишут пачки проверок на входные аргументы, в надежде (без какого-либо формального обоснования), что так или иначе эти проверки поймают все "плохие" случаи

> Парсинг наугад неизбежно лишает программу возможности отвергнуть некорректные данные вместо того, чтобы их обрабатывать. Обнаруженные на поздних стадиях ошибки в переданных данных приводят к тому, что какая-то их часть уже оказывается обработанной, в результате чего итоговое состояние программы тяжело предугадать

> Все места в программе обязаны предполагать, что возникновение исключения в любом месте не просто возможно, но зачастую необходимо

См. подробней статью: [Парсите, а не валидируйте](https://habr.com/ru/post/498042/#:~:text=%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%20%D0%BD%D0%B5%20%D1%81%D0%BA%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D0%B8%D1%80%D1%83%D0%B5%D1%82%D1%81%D1%8F.-,%D0%9E%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8,-%D0%9D%D0%B0%D0%B4%D0%B5%D1%8E%D1%81%D1%8C%2C%20%D0%BA%20%D1%8D%D1%82%D0%BE%D0%BC%D1%83).
</details>

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L33-L35
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L37-L41
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L43-L52
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/view/edit-form-view.js#L54
</details>

Попробуй для создании этой разметки написать функции и вынести их за пределы `createTemplate`, чтобы упростить чтение и переиспользовать код. 

> Нужные для разметки значения получай через параметр функции

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/213419181-849c76a9-f9aa-415c-b98c-5e8f61bb020e.png)

![image](https://user-images.githubusercontent.com/700213/213419138-c474d11b-dce6-4aa9-8d08-bf43ae5b4000.png)

![image](https://user-images.githubusercontent.com/700213/213419181-849c76a9-f9aa-415c-b98c-5e8f61bb020e.png)

![image](https://user-images.githubusercontent.com/700213/213419812-a6480dd4-e4a5-4064-bec4-e194f3b493de.png)
![image](https://user-images.githubusercontent.com/700213/213419835-27742ff6-95cd-42a6-b22a-172cd330ca16.png)

</details>

См. ТЗ:
> Если пользователь внёс изменения в точку маршрута, не выполнил сохранение и пытается перейти к редактированию другой точки маршрута либо создать новую, то **в этом случае открытая форма редактирования скрывается без сохранения изменений**

Нужно доработать.

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/213419906-e80a9ea8-56fe-4ff4-ae9f-738c22d2d669.png)

</details>

См. ТЗ:
> Стоимость. **Целое положительное число**

1. стоимость, введённая в форме редактирования, не сохраняется в данных точки маршрута;
2. форма допускает ввод отрицательных значения стоимости и нуля.

Нужно постараться доработать в этом задание.

> Чтобы сохранить значения стоимости в состояние вью **без перерисовки формы** используй [AbstractStatefulView .`_setState`](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/framework/view/abstract-stateful-view.js#L36-L38)

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      this._state.offers.splice(currentOfferIndex, 1);
`this._state`.offers.splice(currentOfferIndex, 1);

На защите могут придраться к прямой работе с `this._state`, тем более в демо для работы с ним используются спец. метод: [AbstractStatefulView .`_setState`](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/framework/view/abstract-stateful-view.js#L36-L38).

[Б17](https://up.htmlacademy.ru/ecmascript/19/criteries#b17) 
> Приватные и защищённые поля в классах помечены и не используются снаружи

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at #escKeyDownHandler (point-presenter.js:105:17)
```
</details>

В форме редактирования при выборе направления из списка выбрасывается исключение (ошибка).

Нужно разобраться и исправить.

[Б2](https://up.htmlacademy.ru/ecmascript/19/criteries#b2) 
> При выполнении кода не возникает необработанных ошибок

2023-01-19 10:43 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/213421698-d9ba27a4-efb1-42c8-87f0-30476b3d6156.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at #destinationChangeHandler (edit-form-view.js:209:40)
```
</details>

См. ТЗ:
> Пункт назначения. Выбирается из списка предложенных значений, полученных с сервера. **Пользователь не может ввести свой вариант для пункта назначения**

Нужно доработать в этом задание.

[Б2](https://up.htmlacademy.ru/ecmascript/19/criteries#b2) 
> При выполнении кода не возникает необработанных ошибок

2023-01-21 08:08 UTC, AlexMasterov commented on src/view/edit-form-view.js
> стоимость, введённая в форме редактирования, не сохраняется в данных точки маршрута

Это потребуется сделать в след. заданиях.

2023-01-23 09:27 UTC, Domish4 commented
Хаюшки! несмотря на метод reset, данные все равно не сбрасываются. Вторые сутки над проблемой думаю, может не вижу чего-то очевидного?

2023-01-23 15:27 UTC, AlexMasterov requested changes

2023-01-23 15:27 UTC, AlexMasterov commented on src/const.js
> +export {FilterType, SortType, TYPES};
Сейчас `TYPES` экспортируются, но в проекте нигде не используются.

Нужно найти применение или удалить.

> `TYPES` можно использовать для генерации [разметки списка типов формы редактирования](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/view/edit-form-view.js#L37-L41). Сейчас название типов формируется на основе `offer.type`, которых может не быть

[Б18](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода.

2023-01-23 15:27 UTC, AlexMasterov commented on src/const.js
> +const TYPES = ['taxi', 'bus', 'train', 'ship', 'drive', 'flight', 'check-in', 'sightseeing', 'restaurant'];
`TYPES` чего?

В этом модуле желательно уточнить название.

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/8#discussion_r1065761236
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/9#discussion_r1067151884

2023-01-23 15:27 UTC, AlexMasterov commented on src/model/trip-destinations-model.js
> +    return this.#tripDestination;
На это не было замечаний, но здесь случилось не нужное изменение.

```js
Array.isArray(this.#tripDestination) // true
```

[Б8](https://up.htmlacademy.ru/ecmascript/19/criteries#b8) 
> Массивы названы существительными во множественном числе

2023-01-23 15:27 UTC, AlexMasterov commented on src/model/trip-destinations-model.js
> +    return this.#tripDestination;
На это не было замечаний, но здесь случилось не нужное изменение.

get `tripDestination`() {

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/8#discussion_r1065746409

Геттер возвращает массив, но теперь назван в един. числе.

[Б10](https://up.htmlacademy.ru/ecmascript/19/criteries#b10) 
> Название функции или метода должно быть глаголом и соответствовать действию, которое выполняет функция или метод

2023-01-23 15:27 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    pointPresenter.init(pointData, this.#destinationModel);
Не исправлено.

<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-list-presenter.js#L60-L64
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-list-presenter.js#L72
</details>

Обрати внимание, что `pointData` — это объект и он передается первым аргументом в метод `PointPresenter.init`. В этом объекте уже есть `tripDestinations` и `allOffers`. 

Не смотря на то, что эти данные с массивом направлений модели `destinationModel` уже есть в `pointData`, вторым аргументом передаётся сама модель `destinationModel`, которая внутри метода, как его второй параметр, будет названа как массив `tripDestinations`. При этом эта же модель также передается в конструктор `PointPresenter` и там доступна через поле `tripDestinations`, опять же названное, как массив.

В простом решение можно отказаться от передачи модели в конструктор `PointPresenter` (сейчас внутри объекта модель не используется), а передавать из неё массив направлений в метод `PointPresenter.init` (сейчас здесь _дополнительно_ передается сама модель, но под названием массива, что путает). 

<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-presenter.js#L29-L31
</details>

Поскольку массив направлений используется только в `.init` для передачи во вью, то поле `PointPresenter.#tripDestination` избыточно и его можно удалить. 

<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-list-presenter.js#L60-L64
</details>

Объект `pointData` используется как аргумент `PointPresenter.init`, но создается отдельно. Наверное, это продолжает тебя путать, еще с [прошлого замечания](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/9#discussion_r1067170855). Тогда лучше такой объект создать при вызове метода  `PointPresenter.init`.

<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-presenter.js#L42-L46
</details>
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/view/edit-form-view.js#L145
</details>

В добавок ко всем странностям, во конструктор вью `EditFormView` больше не передаются данные из моделей, хотя по сигнатуре конструктора они ожидаются. Это тоже нужно доработать.

<details>
<summary>Пример</summary>

```js
// presenter/point-list-presenter.js
#renderPoint(point) {
  const pointPresenter = new PointPresenter({
    container: this.#tripEventsListView.element,
    onDataChange: this.#handlePointChange,
    onModeChange: this.#handleModeChange,
  });

  pointPresenter.init({
    point,
    destinations: this.#destinations,
    allOffers: this.#allOffers,
  });

  this.#pointPresenters.set(point.id, pointPresenter);
}
```
```js
// presenter/point-presenter.js 
constructor({container, onDataChange, onModeChange}) {
  this.#container = container;
  this.#handlePointChange = onDataChange;
  this.#handleModeChange = onModeChange;
}

init({point, destinations, allOffers}) {
  this.#point = point;

  // ...

  this.#pointFormView = new EditFormView({
    ...point,
    destinations,
    allOffers,
    onFormSubmit: this.#handleSubmitForm,
    onRollupClick: this.#handleCloseForm,
  });
}
```
</details>

> См. также пример решения получше в https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1080989733

2023-01-23 15:27 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-list-presenter.js#L87
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-list-presenter.js#L57-L64
</details>

this.#renderPoint(point, `this.#destinations`, `this.#allOffers`);

Обрати внимание, что в метод `renderPoint` кроме `point` также передается значения из полей `this.#destinations` и `this.#allOffers`, но при этом сам метод имеет сигнатуру только с одним параметром, т.е. эти аргументы не используются. Вместо этого метод внутри себя обращается к этим полям напрямую, используя `this.`.

Поэтому эти неиспользуемые аргументы следует удалить:

```diff
- this.#renderPoint(point, this.#destinations, this.#allOffers);
+ this.#renderPoint(point);
```

[Б18](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

2023-01-23 15:27 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
Лучше оставить прежний вариант 😃

2023-01-23 15:27 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      this.#pointFormView.reset(this.#point);
<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-presenter.js#L74
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-presenter.js#L93
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-presenter.js#L109
</details>

Вызов метода `pointFormView.reset()` повторяется.

[Д11](https://up.htmlacademy.ru/ecmascript/19/criteries#d11) 
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий

Логика ТЗ и реализация класса вполне позволяет сделать _один_ сброс в самом (ключевом) методе `#replaceFormToCard`, а в других местах удалить.

<details>
<summary>Пример</summary>

```js
// presenter/point-presenter.js
#replaceFormToCard() {
  replace(this.#pointCardView, this.#pointFormView);
  document.removeEventListener('keydown', this.#escKeyDownHandler);

  this.#pointFormView.reset(this.#point);
  this.#mode = Mode.DEFAULT;
}
```
</details>

2023-01-23 15:27 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.element.querySelector('.event__available-offers').addEventListener('change', this.#offerChangeHandler);
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1080992889.

В этом замечание специально дана прямая ссылка на реализацию геттера [`this.element`](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/framework/view/abstract-view.js#L30-L36), чтобы увидеть, что происходит _каждый раз_ при обращение к `this.element`.

Там же предложен простой вариант оптимизации:
> Можно получить элемент _один_ раз, используя переменную, и дальше в методе работать с ней

<details>
<summary>Пример простой оптимизации</summary>

```js
// view/edit-form-view.js
_restoreHandlers() {
  const element = this.element;

  element.querySelector('form').addEventListener('submit', this.#formSubmitHandler);
  element.querySelector('.event__rollup-btn')?.addEventListener('click', this.#rollupEventClickHandler);
  element.querySelector('.event__type-group').addEventListener('change', this.#pointTypeChangeHandler);
  element.querySelector('.event__input--destination').addEventListener('change', this.#destinationChangeHandler);
  element.querySelector('.event__available-offers').addEventListener('change', this.#offerChangeHandler);
}
```
</details>

2023-01-23 15:27 UTC, AlexMasterov commented on src/view/edit-form-view.js
> -  const typeOffers = offerByType.offers;
После [исправления в презентерах](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084067382) нужно вернуть, как было.

На это место было другое замечание: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081040653.

2023-01-23 15:27 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this._setState(this._state.offers.splice(currentOfferIndex, 1));
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/view/edit-form-view.js#L222-L229
</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081082100.

В замечание специально была дана ссылка на реализацию [AbstractStatefulView .`_setState`](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/444ab26ac56a7e83e0c1d7f1ee4e51e7b7a9e520/src/framework/view/abstract-stateful-view.js#L36-L38):

```js
/**
  * Метод для обновления состояния
  * @param {Object} update Объект с обновлённой частью состояния
  */
_setState(update) {
  this._state = structuredClone({...this._state, ...update});
}
```

Этот метод в качестве аргумента ожидает получить _объект_, а здесь ему в одном случае передается длина массива (= результат [Array.p.`push`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/push#%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B0%D0%B5%D0%BC%D0%BE%D0%B5_%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5), _число_), а в другом прежний, но измененный, _массив_ (= результат [Array.p.`splice`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B0%D0%B5%D0%BC%D0%BE%D0%B5_%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5)). 

Деструктуризация таких значений ( = `...update`) будет некорректной, что повредит объект состояния  `this._state`. При этом прямая мутация состояния продолжается (= `this._state.offers.push`,  `this._state.offers.splice`); здесь ничего не поменялось, а решение в целом стало хуже.

В этом случае лучше использовать методы `Array`, которые после изменений возвращают _новый_ массив (их нужно знать), или для мутации _сначала_ скопировать массив явно (нужно знать способы копирования). После этого новый массив можно передать, как новое значение `offers`: `this._setState({ offers: ... })`.

<details>
<summary>Пример</summary>

```js
this._setState({
  offers: this._state.offers.concat(currentOfferId)
});

this._setState({
  offers: this._state.offers.slice().splice(currentOfferIndex, 1)
});
```
```js
// view/edit-form-view.js
const { offers } = this._state;

const currentOfferIndex = offers.indexOf(currentOfferId);

const updatedOffers = currentOfferIndex === -1
  ? offers.concat(currentOfferId)
  : offers.slice().splice(currentOfferIndex, 1);

this._setState({ offers: updatedOffers });
```

См. также [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-7/src/model/tasks-model.js#L20-L24).
</details>

Нужно разобраться и доработать, или вернуть, как было изначально.

> Есть решения лучше

2023-01-23 15:27 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  #destinationChangeHandler = (evt) => {
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/view/edit-form-view.js#L196-L218
</details>

Нужно переделать с учетом прошлых замечаний к этому месту.

2023-01-24 10:49 UTC, Domish4 commented on src/view/edit-form-view.js
> +  #destinationChangeHandler = (evt) => {
Я не понимаю( как это должно работать... в 7 ом модуле в задании меняй-удаляй будет задача на валидацию этого инпута.
 "Ограничьте возможность ввода в поле «Пункт назначения» конечным списком городов. Для удобства пользователя в разметке используется datalist для упрощения ввода." при этом я так понимаю там даталист сделан, чтобы чтобы был быстрый поиск по городам, чтобы введя букву С сразу найти Саратов. получается, по логике тогда какая-то возможность ввести свои варианты должна быть... поэтому пользователь может в инпут понаписать всякое, но не сохранить, если такого  пункта назначения нет...

2023-01-24 10:54 UTC, Domish4 commented on src/presenter/point-list-presenter.js
> +    pointPresenter.init(pointData, this.#destinationModel);
Если в point-list-presenter 

> tripDestinations: this.#destinations,

![image](https://user-images.githubusercontent.com/103725377/214273418-b392c1be-e239-41b3-8e69-245e68b4a52f.png)
менять на просто       

> destinations: this.#destinations,


то все рушится, ломается и ничего абсолютно не чинится

2023-01-24 13:13 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    pointPresenter.init(pointData, this.#destinationModel);
В этом примере значение `this.#destinations` задается свойству `destinations`, а не `tripDestinations`. Такое название используется и для конструктора `EditFormView`.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/view/edit-form-view.js#L145

Например, в коде последнего коммита, конструктор `EditFormView` ожидает объект со свойством `tripDestinations`, а в моем примере используется название `destinations`.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/eaeb3e61433b630a1d6429f3f8d3aee100ea0613/src/presenter/point-presenter.js#L42-L46

Обрати внимание, что при вызове конструктора `EditFormView` ничего кроме `point` и коллбэков не передается, т.е. свойства `tripDestinations` нет изначально (и во вью оно `undefined`, наверное поэтому в `createTemplate()` такая [зависимость от проверок `?.`](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081049355)). В моем примере это исправлено.

> По учету этих исправлений во `createTemplate()` см. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084152964

Тебе нужно в своем актуальном коде (который я не вижу) проследить передачу/проброс значения `this.#destinations` до `EditFormView` под корректным названием свойства или в самих презентерах использовать название `tripDestinations`, чтобы не менять во `EditFormView`, т.е. скорректировать мой пример, адаптируя его под свой _актуальный_ код.

> Подобное не должно быть проблемой, если использовать отладку: `debagger` или `console.log`. См. [Знакомство с DevTools](https://up.htmlacademy.ru/javascript/27/book/8.1) и [Отладка в браузере](https://learn.javascript.ru/debugging-chrome)

2023-01-24 13:18 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    pointPresenter.init(pointData, this.#destinationModel);
> то все рушится, ломается и ничего абсолютно не чинится

Что написано в консоли?

Пожалуйста, покажи, как у тебя сейчас выглядит `PointPresenter.init` и конструктор `EditFormView`.

2023-01-24 13:22 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      destinations: this.#tripDestinations
ref: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1085301747

Обрати внимание, что здесь в конструктор `TripEventItemView` значение `this.#tripDestinations` передается, как `destinations`:
```js
destinations: this.#tripDestinations
```
На этом и был основан [мой пример.](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084067382)

2023-01-24 15:44 UTC, Domish4 commented on src/view/edit-form-view.js
Это кстати тоже делается в следующем задании! в этом надо лишь реализовать чтобы выбранные офферы не сохранялись при смене типа ивента,
> Обратите внимание, что при смене дополнительных опций ранее выбранные пользователем значения не сохраняются, а ещё выбор дополнительных опций не влияет на стоимость, указанную в соответствующем поле ввода.

 так что если это не критично я сделаю это как раз в седьмом модуле!

2023-01-24 15:48 UTC, Domish4 commented on src/presenter/point-list-presenter.js
> +    pointPresenter.init(pointData, this.#destinationModel);
Вроде бы поправила, но не уверена )

2023-01-25 01:58 UTC, AlexMasterov requested changes
К сожалению, нужно доработать.

Многие замечания повторяются и почти все они уровня JS1, а по некоторым реализованным пунктам ТЗ случился скрытый регресс. Видео прилагается 😟


https://user-images.githubusercontent.com/700213/214467266-2da03d9a-8b24-4eca-8aaa-4e508076dcc3.mp4

2023-01-25 01:58 UTC, AlexMasterov commented on src/utils/common.js
> +//const destinationInfo = tripDestinations.find((item) => item.id === destination);
`//`

Нужно удалить.

[Б18](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function getPicturesListTemplate(picture) {
function `get`PicturesListTemplate(picture) {

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/5#discussion_r1061675421

В проекте подобные функции начинаются с глагола `create`, а здесь внезапно используется `get`.

[Д6](https://up.htmlacademy.ru/ecmascript/19/criteries#d6) 
> Используется единый стиль именования переменных

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function tripTypeTemplate(allOffers, point, type) {
function  `tripTypeTemplate`

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1051285240.

[Б10](https://up.htmlacademy.ru/ecmascript/19/criteries#b10) 
> Название функции или метода содержит глагол [в начале]

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function offersTemplate(offerByType, offers) {
function `offersTemplate`

[Б10](https://up.htmlacademy.ru/ecmascript/19/criteries#b10) 
> Название функции или метода содержит глагол [в начале]

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  return offerByType.offers.map((offer) =>
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L47-L51
</details>

`offer.*`

См. [деструктуризацию в параметре функции](https://learn.javascript.ru/destructuring-assignment#ostatok-obekta:~:text=%D0%9D%D0%B0%20%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%20%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B4%D0%B8%D1%82%20%D0%B4%D0%B5%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F!).

Нужно больше практике:
```diff
- .map((offer) =>
+ .map(({ id, title, price }) =>
```
\+ сразу передавай в функцию `offers`

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function createTemplate(point, tripDestinations, allOffers, isEdit) {
createTemplate(`point`, tripDestinations, allOffers, `isEdit`) {

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L165

Теперь в `createTemplate()` первым аргументом передается объект _состояния_ (= `this._state`), а не `point`. 

Нужно уточнить название.

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/214456813-639dbef4-6f78-471a-813a-20ffe06938cf.png)

</details>

Сейчас форма снова отображается в режиме создания новой точки маршрута.

При вызове `createTemplate()` передается только 3 аргумента и таким образом значение 4-го параметра всегда `undefined`, что ломает логику выбора шаблона для режимов формы.
```js
isEdit // undefined
```

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L244-L246

Свойство `isEdit` есть у `this._state`, которое доступно внутри функции через 1-й параметр. Его не нужно передавать отдельно.

> См. пример https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086140749

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    element.querySelector('.event__input--destination').addEventListener('select', this.#destinationChangeHandler);
.addEventListener(`'select'`, this.#destination`Change`Handler);

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1080996736

[Д4](https://up.htmlacademy.ru/ecmascript/19/criteries#d4) 
> Из названия обработчика события и функции-колбэка следует, что это за обработчик

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    return {...state};
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L244-L246
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L249-L251
</details>

EditFormView.`parsePointToState()` создает объект состояния (= `this._state`), копируя в него свойства из объекта `point` и добавляя свои, как здесь `isEdit`. EditFormView.`parseStateToPoint()` делает тоже самое, но в обратную сторону.

Проблема в том, что сейчас EditFormView.`parseStateToPoint()` возвращает объект `point` с лишним свойством `isEdit`. 

Все лишние свойства нужно удалить.

> См. [вариант решения в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-6/src/view/task-edit-view.js#L294)

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    if (evt.target.value === 0) {
if (evt.target.`value` === `0`) {

Свойство `.value`, представляя атрибут тега `value`, указывает на _строку_,

Таким образом, здесь в условие _строка_ всегда сравнивается с _числом_, что всегда будет возвращать `false` и код в ветки условия _никогда_ не будет выполнен (= недостижим).

Нужно разобраться и исправить.

[Б20](https://up.htmlacademy.ru/ecmascript/19/criteries#b20) 
> В коде нет заранее недостижимых участков кода

[Б24](https://up.htmlacademy.ru/ecmascript/19/criteries#b24) 
> Отсутствуют потенциально некорректные операции

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      .find((destination) => evt.target.value === destination.name);
.find((destination) => `evt.target.`value === destination.name);

В цикле значение `evt.target.value` не меняется, но его получение происходит повторно, через цепочку обращений двух объектов: `evt.` и `target.`, что неэффективно и ухудшает читаемость.

См. повторно https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084146747.

<details>
<summary>Пример простой оптимизации</summary>

```js
const destinationName = evt.target.value;

this.#tripDestination.find(({ name }) => name === destinationName);
```
</details>

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      if (e instanceof TypeError) {
На всякий случай повторю, что в доработанном решение не должно быть `try catch`, особенно с проверкой на `TypeError`. В противном случае, сохранив такое решение, придаться исправлять каскад (формальных) замечаний и "краснеть" на защите.

Если `.find` по коллбэку не находит объект `destination` и возвращает `undefined`, то достаточно проверить на него или сразу вернуть пустую структуру `destination` и строить условия на основе неё и полей.

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/5#discussion_r1059070130 (Пример решения без `.?`)

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +            <input class="event__input  event__input--price" id="event-price-1" type="number" name="event-price" value="${basePrice}">
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/214455067-241ed1ba-e96e-494f-b2ca-d1f23b19ff04.png)

</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081076864:
> форма допускает ввод отрицательных значения стоимости и нуля

Нужно отграничить ввод, например, с помощью спец. атрибутов, или реализовать валидацию, чтобы по его эффекту или сообщению можно было понять о недопустимом значении стоимости, например, с помощью [AbstractView.`shake`](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/master/src/framework/view/abstract-view.js#L52-L62).

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const offerByType = allOffers.find((offer) => offer.type === type);
После избавления от `?.` нужно здесь обработать случай, когда `.find` ничего не находит и возвращает `undefined`. 

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/5#discussion_r1059070130 (hint -> Пример решения без `.?`).

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    template = picture.pictures?.map((elem) => `<img class="event__photo" src=${elem.src} alt="${elem.description}">`
`elem`

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054457172
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1055938953

[`Б 4`](https://up.htmlacademy.ru/ecmascript/19/criteries#b4)
> Сокращения в словах запрещены

Почему `elem`, а не `item`, или здесь более конкретный `picture` 🤔

Можно вообще избежать мук именования, см. [деструктуризацию в параметре функции](https://learn.javascript.ru/destructuring-assignment#ostatok-obekta:~:text=%D0%9D%D0%B0%20%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%20%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B4%D0%B8%D1%82%20%D0%B4%D0%B5%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F!).

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    template = picture.pictures?.map((elem) => `<img class="event__photo" src=${elem.src} alt="${elem.description}">`
`picture`.pictures`?.`map

> Снова `?.` 😟

`picture` — это значение `destinationInfo`:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L133

Нужно уточнить название, а еще лучше сразу передать в функцию массив изображений: `destinationInfo.pictures`.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L29-L32

Получается, что _вся_ полезная работа функции зависит от наличие значения в параметре. Может пользователю этой функции просто не нужно её вызывать с пустым массивом🤔

Проверку нужно убрать, а если нужна оптимизации, то:

```js
const { pictures } = destinationInfo;

// ....

${pictures.length > 0 ? getPicturesListTemplate(pictures) : ''}
```

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +            ${offersTemplate(offerByType, offers)}
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L44-L54
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L115-L119
</details>

`offersTemplate.length > 0`

Сейчас `offersTemplate` — это _функция_ и у неё нет свойства `.length`.

> Что здесь происходит. Неужели снова _так_ путает название 🤔

В отсутствие предложений секция `Offers` перестала скрываться, как требует ТЗ и было реализовано ранее.

Нужно разобраться и исправить.

[Б24](https://up.htmlacademy.ru/ecmascript/19/criteries#b24) 
> Отсутствуют потенциально некорректные операции

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +            <p class="event__destination-description">${destinationInfo.description}</p>
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L127

```js
const { description, pictures } = destinationInfo;

// ...

<p class="event__destination-description">${description}</p>
```

2023-01-25 01:58 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +    this.#tripDestinations = tripDestinations;
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084067382:
> Поскольку массив направлений используется только в `.init` для передачи во вью, то поле `PointPresenter.#tripDestination` избыточно и его можно удалить

Поле ` this.#point` используется для метода `.reset`, чтобы сбросить несохраненную форму. `allOffers` и `tripDestinations` нужны только в `.init` и больше нигде не используются. Поэтому не нужно лишний раз сохранять их в объекте.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-presenter.js#L32-L33

Нужно удалить.

2023-01-25 01:58 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      ...allOffers,
<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-presenter.js#L39-L40
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-presenter.js#L47-L48
</details>

```js
tripDestinations // undefined 
allOffers        // undefined
```

В метод `PointPresenter.init()` передается _один_ параметр и это объект:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-list-presenter.js#L64-L68

Но сам метод ожидает 3 параметра, 2 из которых `undefined`:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-presenter.js#L30

> См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084127755

См. внимательно [мой пример](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084067382) и [деструктуризацию в параметре функции](https://learn.javascript.ru/destructuring-assignment#ostatok-obekta:~:text=%D0%9D%D0%B0%20%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%20%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B4%D0%B8%D1%82%20%D0%B4%D0%B5%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F!).

2023-01-25 01:58 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      <input class="event__input  event__input--destination" id="event-destination-1" type="text" name="event-destination" value="${destinationInfo.name}" list="destination-list-1" pattern="^(${CITIE
pattern="^(${`CITIES_NAMES`})$

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/const.js#L11

Не понимаю, зачем это нужно. Тем более, фикс. значения. Надеюсь, что это пробный вариант обработать ввод направления.

`CITIES`_NAMES

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1055723012 😃

2023-01-25 02:11 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  static parsePointToState = (point) => ({ ...point });
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L243-L247
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L59
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/view/edit-form-view.js#L62
</details>

<details>
<summary>Пример, что ожидалось в простом случае</summary>

```js
this._setState(EditFormView.parsePointToState(point, tripDestinations));
```
```js
 static parsePointToState(point, tripDestinations) { 
   const destinationId = point.destination;

   return { ...point, 
     isEdit: Object.hasOwn(point, 'id'),
     destinationNames: tripDestinations.map({ name }) => name),
     destinationInfo: tripDestinations.find(({ id }) => id === destinationId),
   }; 
 } 
```
```js
function createTemplate(state) {
  const { isEdit, destinationNames, destinationInfo, ...point } = state;
  const { basePrice, type, destination, offers, dateFrom, dateTo } = point;

  // ...

  const destinationsOptionValueTemplate = destinationNames.map((name) => `<option value="${name}"></option>`).join('');
}
````

Тоже самое с `allOffers`.

> См. [Остаток объекта «…»](https://learn.javascript.ru/destructuring-assignment#ostatok-obekta)
</details>

2023-01-25 02:17 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  #destinationChangeHandler = (evt) => {
С учетом новых замечаний это лучше отложить до следующего задания.

По вариантам реализации наглядно поясню немного позже.

2023-01-25 02:25 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-presenter.js#L31
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/f356c7351a5a989472cfa600ffd51fa769b4b0c3/src/presenter/point-presenter.js#L80
</details>

Сейчас `point` (и `this.#point` соответственно) — это объект с полями `point`, `allOffers`, `tripDestinations`.

См. подробней описание проблемы и решение в https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086123623.

2023-01-25 13:34 UTC, AlexMasterov requested changes

2023-01-25 13:34 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +    if (evt.key === 'Esc' || evt.key === 'Escape') {
😟

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084134948.

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const { name: descriptionName, description, pictures} = tripDestinations.find((item) => item.id === destination) ?? BLANK_DESTINATION;
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/view/edit-form-view.js#L15-L21
</details>

Сейчас `BLANK_DESTINATION` содержит _лишние_ поля от структуры `Offer`.

В похожем случае, для обработки отсутствия результата `allOffers.find` нужно создать _отдельную_ пустую структуру `Offer`, а не использовать структуру `Destination` (`BLANK_DESTINATION`).

<details>
<summary>Пример</summary>

См. структуру `Offer` в ТЗ и тестовых данных:

```js
const BLANK_OFFER = {
  type: '',
  offers: [],
};
```
</details>

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +              <img class="event__type-icon" width="17" height="17" src="img/icons/${offersType}.png" alt="Event type icon">
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/view/edit-form-view.js#L58
</details>

Здесь вместо `offersType` следовало использовать значение выбранного типа из данных точки маршрута `point.type`, как было раньше.

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    offersName ?
Снова неявная проверка на пустую строку 😟

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081008742.

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      element.querySelector('.event__rollup-btn').addEventListener('click', this.#rollupEventClickHandler);
**2x** element.`querySelector('.event__rollup-btn')`

См.: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/7#discussion_r1064690122.

[Д18](https://up.htmlacademy.ru/ecmascript/19/criteries#d18) 
> Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      element.querySelector('.event__available-offers').addEventListener('change', this.#offerChangeHandler);
**2x** element.`querySelector('.event__available-offers')`

См.: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/7#discussion_r1064690122.

[Д18](https://up.htmlacademy.ru/ecmascript/19/criteries#d18) 
> Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    if (selectedDestination !== undefined) {
if (selectedDestination `!== undefined`) {

В таком условие можно убрать явную проверку.

> Для явной проверки лучше привести отсутствие результата `.find` к `?? null` или `?? BLANK_DESTINATION`, поскольку здесь точно известно, что в массиве _объект_, а проверять так:  `if (selectedDestination !== null)` или  `if (selectedDestination.name !== '')`. См. [пример](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/view/edit-form-view.js#L59)

[Д10](https://up.htmlacademy.ru/ecmascript/19/criteries#d10) 
> В проекте не должно быть избыточных проверок

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  }
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/view/edit-form-view.js#L239-L243
</details>

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054462344

Нужно вернуть из функции `point` 😃

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        pictures: []
`pictures: []`

Здесь _в корень_ объекта `this._state` добавляется лишние свойство `pictures`, которое должно быть (и берется) у объекта `destination`.

> Уже было такое с `isEdit` 😃

Нужно удалить:
```diff
- pictures: []
```

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        <input class="event__offer-checkbox  visually-hidden" id="event-offer-${title}-${id}" type="checkbox" name="event-offer-${title}" ${offers.includes(id) ? 'checked' : ''} data-offer-id="${id}"
<details>

<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/214570527-7c804411-ee2e-4bcc-a1fb-80fa64b3d498.png)

</details>

Выбранные предложения не отмечаются, как раньше.

`offers.includes(id)`

Нужно искать `id` в `points.offers`, а не в `offers`, по которому происходит итерация. 

<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/view/edit-form-view.js#L117
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/view/edit-form-view.js#L40-L43
</details>

`point.offers` передается в функцию вторым аргументом, нужно внутри функции получить его через второй параметр (нужно добавить) и использовать этот массив для `.includes`.

2023-01-25 13:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/214572231-afc9b33c-8024-460b-b98b-388de96a202c.png)

</details>

См. ТЗ:
> Одновременно может быть открыта только одна форма создания/редактирования

> Если пользователь внёс изменения в точку маршрута, не выполнил сохранение и пытается перейти к редактированию другой точки маршрута либо создать новую, то в этом случае открытая форма редактирования скрывается без сохранения изменений. После открывается другая форма редактирования или форма создания новой точки маршрута

<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/presenter/point-presenter.js#L103-L106
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/67ca624fb288648e47f4b798bdcc41d7e72b82b3/src/presenter/point-presenter.js#L82-L87
</details>

Сейчас при нажатии на кнопку с крышкой коллбэк `this.#handleModeChange()` срабатывает дважды. Из-за этого получается открыть более одной формы.

Нужно:
1. в  `#handleOpenForm()` убрать `this.#handleModeChange()`
2. в  `#replaceCardToForm()` вызывать `this.#handleModeChange()` перед заменой элемента, т.е. в начале функции

2023-01-25 13:34 UTC, AlexMasterov commented on src/presenter/point-presenter.js
Сейчас сброс формы не работает только в случае (пере)открытия одной и той же формы по нажатию на крышку и на кнопку `Save`, потому что в `this.#replaceFormToCard()` не вызывает сброс.

Нужно доработать.

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084140333, чтобы избежать дублирования и _повторного_ вызова сброса

2023-01-25 13:41 UTC, AlexMasterov commented
Нужно еще немного доработать и можно двигаться дальше.

Вижу, что не была учтена большая часть замечаний — это может усложнить доработку проекта, потому что некоторый код и сами решения имеют высокую стоимость изменений; такой код просто невозможно изменять и расширять. Это риск, но времени уже мало.

2023-01-25 13:45 UTC, AlexMasterov commented on src/view/edit-form-view.js
Сейчас сброс формы не работает только в случае (пере)открытия одной и той же формы по нажатию на крышку и на кнопку `Save`, потому что в `this.#replaceFormToCard()` не вызывает сброс.

Нужно доработать.

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084140333, чтобы избежать дублирования и _повторного_ вызова сброса

2023-01-26 11:19 UTC, Domish4 commented
Вроде бы все работает... да, там есть закомменченный код, я все почищу потом

2023-01-26 14:35 UTC, AlexMasterov commented
👍🏻

2023-01-26 14:35 UTC, merged

2023-01-26 14:37 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +const BLANK_DESTINATION = {
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086590412
> Сейчас `BLANK_DESTINATION` содержит _лишние_ поля от структуры `Offer`

Лишние поля нужно удалить.

2023-01-26 14:47 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      eventRollupBtn.addEventListener('click', this.#rollupEventClickHandler);
В этом случае лучше вернуть, как было с `?.`:
```js
element.querySelector('.event__rollup-btn')?.addEventListener('click', this.#rollupEventClickHandler);
```

2023-01-26 14:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    if (selectedDestination !== null) {
Во многих замечаниях напоминал (и давал ссылку на документацию), что `.find` возвращает `undefuned`.

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086597670:
> Для явной проверки лучше привести отсутствие результата `.find` к `?? null` или `?? BLANK_DESTINATION`, поскольку здесь точно известно, что в массиве объект, а проверять так: `if (selectedDestination !== null) `или if `(selectedDestination.name !== '')`

Если хочешь использовать такую проверку, то прежде нужно сделать так:
```diff
- this.#tripDestinations.find((destination) => evt.target.value === destination.name)
+ this.#tripDestinations.find((destination) => evt.target.value === destination.name) ?? null;
```

2023-01-26 14:52 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    point.isEdit ?
Выбор доп. предложений должен быть доступен в форме создании новой точки маршрута.

Нужно разобраться и исправить.

2023-01-26 14:54 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function createPicturesListTemplate(picture) {
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/Domish4/2073335-big-trip-simple-19/blob/e2adbfb793d0cb6f5ede5e1be017a93c4ab2a722/src/view/edit-form-view.js#L30-L37
</details>

Пожалуйста, см. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086112600.

2023-01-26 14:56 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const { basePrice, destination, dateFrom, dateTo, type} = point;
function createTemplate(`point`, tripDestinations, allOffers) {

Это не `point`.

Пожалуйста, см. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1085747596

2023-01-26 14:58 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +    if (evt.key === 'Esc' || evt.key === 'Escape') {
😟

2023-01-26 15:03 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    const selectedDestination = this.#tripDestinations.find((destination) => evt.target.value === destination.name);
.find((destination) => `evt.target.value` === destination.name);

Пожалуйста, см. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086089990.

2023-01-26 17:10 UTC, Domish4 commented on src/view/edit-form-view.js
> +function createTemplate(point, tripDestinations, allOffers, isEdit) {
Нужно уточнить название в смысле переименовать `createTemplate()`?

2023-01-26 17:20 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function createTemplate(point, tripDestinations, allOffers, isEdit) {
Для начала:
```diff
- function createTemplate(point, tripDestinations, allOffers
+ function createTemplate(state, tripDestinations, allOffers
```