Обновление века ч2
htmlacademy-ecmascript/2073335-big-trip-simple-19 pull request #12
Opened 2023-01-27 09:11 UTC by Domish4

2023-01-27 11:22 UTC, AlexMasterov requested changes

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    offers: [],
Поле `offers` находится в структуре `Offer`:

<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/08f7be0458d9ddc493bc8db6121c0b01cc3eefd5/src/view/edit-form-view.js#L24-L27
</details>

Нужно удалить еще одно лишние поле `offers` из структуры `BLANK_DESTINATION` (`Destination`).

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        <input class="event__offer-checkbox  visually-hidden" id="event-offer-${title}-${id}" type="checkbox" name="event-offer-${title}" ${offerByType.type.includes(offerByType.type) ? 'checked' : '
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/215070270-431d2142-f8f3-4a31-ab64-a3d5f2b0861f.png)

</details>


Отображение выбранных предложений всё еще не исправлено; сейчас все предложения отображаются выбранными.

`offerByType.type.includes(offerByType.type)`

Теперь в строке с названием типа происходит поиск подстроки с этим же названием, т.е. в строке `bus` происходит проверка включения в неё подстроки `bus`.

> В прошлых раз в массиве всех предложений с объектами `Offer` (= `[{ id, type, offers }, ...]` был поиск с проверкой включения в этом массиве числового `id`, когда его элементы — это объекты, а не числа

См. внимательно https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1086615640:
> Нужно искать `id` в `point.offers`, а не в `offerByType.offers`, по которому происходит итерация


Попробуй изучить свой прошлый рабочий код, который был написан во втором модуле:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/edit-form-view.js#L23

`offers.includes(offer.id)`

Нужно разобраться и исправить.

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  // const destinationInfo = tripDestinations.find((item) => item.id === destination);
`//`

[Б18](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, которые не используются, **включая закомментированные участки кода**

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    //  const destinationId = point.destination;
`//`

Здесь и ниже.

[Б18](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
>        eventAvailableOffers.addEventListener('change', this.#offerChangeHandler);
В этом месте следовало тоже учесть замечание: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1087945992.

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const { basePrice, destination, dateFrom, dateTo, type} = point ?? createEmptyPoint();
См. конструктор класса:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/08f7be0458d9ddc493bc8db6121c0b01cc3eefd5/src/view/edit-form-view.js#L157

Результат работы `createEmptyPoint()` уже задается, как значение по умолчанию.

Здесь же подобного делать не нужно: (отчасти в этом смысл)
```diff
- const { basePrice, destination, dateFrom, dateTo, type} = point ?? createEmptyPoint();
+ const { basePrice, destination, dateFrom, dateTo, type} = point;
```

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.#setDateToPicker();
Нужно снова проверить весь класс на критерий.

[Д8](https://up.htmlacademy.ru/ecmascript/19/criteries#d8)
> Методы внутри классов упорядочены

```
3. Основные методы класса
4. Обработчики событий [DOM]
5. Статические методы
```

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    removeElement = () => {
removeElement = `() => {`

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081021246

Можно без стрелки, как в род. классе фреймворка:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/08f7be0458d9ddc493bc8db6121c0b01cc3eefd5/src/framework/view/abstract-view.js#L48-L50

~Д5

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/08f7be0458d9ddc493bc8db6121c0b01cc3eefd5/src/view/edit-form-view.js#L266
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/08f7be0458d9ddc493bc8db6121c0b01cc3eefd5/src/view/edit-form-view.js#L280

Тоже самое.

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
>        dateFrom: userDate
Клик по предложению добавляет его полю атрибут `checked`, после чего браузер используя правила в стилях выделяет его цветом. В таком случае браузер своим действием по умолчанию сам перерисововает выбор предложений и поэтому нам не требуется перерисововать _всю форму_ с помощью метода `.updateElement`.

Поля с датами управляются и _так же_ перерисоваются библиотекой `flatpickr`.

this.`updateElement`(

В этом случае тоже можно обновить в состояние вью только данные с датой, избежав полной перерисовки всей формы. Именно для таких случае на прошлом задание был сделан фокус на спец. методе `.setState`:

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1081082100
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/11#discussion_r1084154767

Если нужно обновить настройку у экземпляра `flatpickr` , которая была задана при его создание, то для этого есть спец. метод [`.set`](https://flatpickr.js.org/instance-methods-properties-elements/#retrieving-the-flatpickr-instance:~:text=in%20most%20cases.-,set(option%2C%20value),-%23):

```js
this.#datepickerTo.set('minDate', ...)
```
> Советую ознакомиться с документацией `flatpickr`

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
Если в форме изменить значение стоимости, то при изменение других значений она будет сбрасываться, возвращаясь к исходному значению.

Нужно разобраться и доработать.

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
См. ТЗ:
> Дата и время окончания события. Формат и требования аналогичны дате начала. **Дата окончания не может быть меньше даты начала события**

Не получается проверить; не получается даже просто выбрать дату и сделать так, чтобы она произвольно не поменялась 🤔

Нужно разобраться и доработать.

2023-01-27 11:22 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/215072241-ef9417b8-826f-4798-8e46-4d72b6748730.png)
![image](https://user-images.githubusercontent.com/700213/215072271-fcd7bdcf-beae-4b6e-933f-befc9defebba.png)
![image](https://user-images.githubusercontent.com/700213/215072288-572f6218-8230-4109-8856-bce9a704aa22.png)

</details>

Открытие и закрытие окна выбора даты приводит к произвольной смене даты, причем обоих.

> Этим невозможно пользоваться и тем более проверить

Нужно разобраться и исправить.

2023-01-27 18:40 UTC, AlexMasterov reviewed
Не исправлены ключевые замечания по заданию и пунктам ТЗ, по которым случился регресс 🤔

2023-01-27 18:40 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/87c2cf0ecff06eb4e58c91f7bacedb0da4be2f6c/src/view/edit-form-view.js#L61
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/87c2cf0ecff06eb4e58c91f7bacedb0da4be2f6c/src/view/edit-form-view.js#L63
</details>

[Д11](https://up.htmlacademy.ru/ecmascript/19/criteries#d11) 
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий

2023-01-27 18:40 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        <input class="event__offer-checkbox  visually-hidden" id="event-offer-${title}-${id}" type="checkbox" name="event-offer-${title}" ${point.offers.includes(id) ? 'checked' : ''} data-offer-id="
data-offer-id="${`offers.id`}"

Теперь в качестве `offers.id` используется значение `undefined`.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/87c2cf0ecff06eb4e58c91f7bacedb0da4be2f6c/src/view/edit-form-view.js#L260

```js
currentOfferId // undefined
```

Перестало работать сохранение выбора предложений.

2023-01-27 18:53 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  // const destinationInfo = tripDestinations.find((item) => item.id === destination);
Не исправлено.

2023-01-27 18:53 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    //  const destinationId = point.destination;
Не исправлено.

2023-01-27 19:03 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/215172131-8d17c2cd-66c9-4ac3-8616-9e178a58f627.png)
![image](https://user-images.githubusercontent.com/700213/215172603-4b34f81e-eb7d-47f0-a7cc-01a7a22ba0de.png)
![image](https://user-images.githubusercontent.com/700213/215172643-e37bae6f-65f6-44b1-b313-d9d36b574a95.png)

</details>

Сейчас можно указать дату начала события позднее даты окончания.

См. ТЗ:
> Дата окончания не может быть меньше даты начала события

2023-01-27 22:11 UTC, AlexMasterov commented on src/view/edit-form-view.js
Не исправлено.

2023-01-28 13:39 UTC, Domish4 commented on src/view/edit-form-view.js
То есть проблема в том, что инпут форма не обновляется когда дата окончается сбрасывается?

2023-01-28 22:07 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/87c2cf0ecff06eb4e58c91f7bacedb0da4be2f6c/src/view/edit-form-view.js#L87
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/87c2cf0ecff06eb4e58c91f7bacedb0da4be2f6c/src/view/edit-form-view.js#L249-L256
</details>

Думаю, что для выбора направления можно оставить такое решение. 

Только нужно сделать поле обязательным, добавив в его разметку атрибут `required`, чтобы работала валидация от браузера и было нельзя сделать `submit` (= `Save`) формы с пустым полем.

2023-01-29 06:24 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Пример</summary>

![flatpickr_issue_01](https://user-images.githubusercontent.com/700213/215298995-a4902663-9cab-44d7-a2a8-c4ad59e77d8d.gif)

</details>

1. Форма _позволяет_ выбрать начальную дату позднее (больше) даты окончания;
2. Форма сохраняет невалидную пару дат в состояние вью, позволяя также сохранит их в данных точки маршруты, которые могут быть отправлены на сервер;
3. Выбор невалидной начальной даты произвольно изменяет дату окончания в поле формы, которая была выбрана пользователем, что на JS1 считалось плохим UX:
> Даже если уже выбранное значение не попадает под новые ограничения, не стоит без ведома пользователя изменять значение поля. Пусть ошибку отловит валидация формы
4. Если после выбора невалидной начальной даты открыть и закрыть окно выбора даты окончания, то она снова произвольно изменяется в сторону увеличения, но теперь эта дата сохраняется в состояние вью, см. снова пункт 2.

> То есть проблема в том, что инпут форма не обновляется когда дата окончания сбрасывается?

Это скорее проблема UX, а настоящая проблема не там, где боль 😃

<details>
<summary>hint</summary>

В таком решение проще всего ограничить выбор `max` значения начальной даты, используя значение даты окончания, как это сделано с самой датой окончания, только наоборот:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/87c2cf0ecff06eb4e58c91f7bacedb0da4be2f6c/src/view/edit-form-view.js#L223

</details>

2023-01-29 06:44 UTC, AlexMasterov commented on src/view/edit-form-view.js
В таком решение название направление, которого нет в данных с сервере, не отобразиться в поле. Поэтому можно не экранировать вывод названия направления с помощью библиотеки `he`, разве что сделать это "под задание".

Оставляю это на твое усмотрение 😃

2023-01-30 10:27 UTC, Domish4 commented on src/view/edit-form-view.js
setstate надо сделать у ` #dateFromChangeHandler ` и ` #dateToChangeHandler` или только у первого? шото мозг поплыл и не понимаю.

2023-01-30 10:38 UTC, AlexMasterov commented on src/view/edit-form-view.js
У обоих 😃

<details>
<summary>Пример</summary>

```js
#dateFromChangeHandler = ([dateFrom]) => {
  this.#datepickerFrom .set('minDate', dateFrom);
  this._setState({ dateFrom });
};

#dateToChangeHandler = ([dateTo]) => {
  this.#datepickerTo.set('maxDate', dateTo);
  this._setState({ dateTo });
};
```
> Обрати внимание, что в примере в параметре переименовал название первого элемента массива `[userDate]` в `[dateFrom`] и `[dateTo]`, чтобы вместо `this._setState({ dateFrom: userDate })` сразу писать `this._setState({ dateFrom })`
</details>

2023-01-30 10:41 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        <input class="event__offer-checkbox  visually-hidden" id="event-offer-${title}-${id}" type="checkbox" name="event-offer-${title}" ${point.offers.includes(id) ? 'checked' : ''} data-offer-id="
Нужно использовать `id` из `offer`:

```diff
- data-offer-id="${point.id}
+ data-offer-id="${id}
```

2023-01-30 10:44 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +        minDate: this._state.dateFrom,
> Суровый UX

Это явно лишние и лучше убрать:

```diff
- minDate: this._state.dateFrom,
```

2023-01-30 10:49 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      basePrice: evt.target.value,
Какой тип у значение evt.target`.value`, а какой у `basePrice`?

2023-01-30 10:52 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  #dateFromChangeHandler([userDate]) {
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/371bef314b93fe03714c9576b6dcff90818ba272/src/view/edit-form-view.js#L281-L285
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/371bef314b93fe03714c9576b6dcff90818ba272/src/view/edit-form-view.js#L225
</details>

Нужно обновить ограничение по дате.

См. пример: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/12#discussion_r1090447956.

2023-01-30 11:04 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.#setDateToPicker();
`dateFrom`: `dateFrom`

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/12#discussion_r1090447956:
> Обрати внимание, что в примере в параметре переименовал название первого элемента массива `[userDate]` в `[dateFrom]` и `[dateTo]`, чтобы вместо `this._setState({ dateFrom: userDate })` сразу писать `this._setState({ dateFrom })`

Это фича ES6+:
```diff
- dateFrom: dateFrom
+ dateFrom
```

`this.#setDateToPicker();`

Не нужно пересоздавать объект `flatpickr`, чтобы изменить ограничение. Обручение (и другие настройки) можно менять у готовых объектов, используя спец. метод `.set()`:

```js
this.#datepickerFrom.set('minDate', dateFrom);
```

2023-01-30 11:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    return offerByType.offers.map(({title, price, id}) =>
function createOffersTemplate(`offerByType`, `offers`, point) {

```js
offerByType.offers === offers // true
```

Один параметр можно убрать:
```diff
- function createOffersTemplate(offerByType, offers, point) {
+ function createOffersTemplate(offers, point) {
```

2023-01-30 11:34 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    return offerByType.offers.map(({title, price, id}) =>
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/17660c95e7c0bfc04554b2137980f0a7cc759e6d/src/view/edit-form-view.js#L61

Надо было здесь переменную назвать иначе, например `typeOffers`, чтобы избежать коллизии имен с `offers` из точки маршрута и путаницы в коде.

Из-за неудачного названия далее в коде и в функциях непонятно, какой именно это `offers`.

2023-01-30 12:29 UTC, AlexMasterov approved these changes
![image](https://user-images.githubusercontent.com/700213/215477151-b8009ca7-3b5b-4b8d-a6fb-7578ebfcbd10.png)

2023-01-30 12:29 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/3a68adf04ee5dac37f14f734d83181af39b6b999/src/view/edit-form-view.js#L35
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/3a68adf04ee5dac37f14f734d83181af39b6b999/src/view/edit-form-view.js#L76
</details>

3-й аргумент не используется, нужно удалить:

```diff
-  ${createTripTypeTemplate(allOffers, point, type)} 
+  ${createTripTypeTemplate(allOffers, point)} 
```

2023-01-30 12:29 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      basePrice: Number(evt.target.value)
👍🏻

<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/3a68adf04ee5dac37f14f734d83181af39b6b999/src/view/edit-form-view.js#L103
</details>

У DOM-элемента поля с типом `number` есть свойство, которое сразу возвращает _числовое_ значение поля:

 
```diff
- basePrice: Number(evt.target.value)
+ basePrice: evt.target.valueAsNumber
```

2023-01-30 12:29 UTC, merged

2023-01-30 12:44 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    offerByType.offers.length > 0 ?
```diff
- offerByType.offers.length > 0 ?
+ typeOffers.length > 0 ?
```

2023-01-30 12:49 UTC, AlexMasterov commented on src/view/edit-form-view.js
>              <input class="event__input  event__input--price" id="event-price-1" type="number" name="event-price" min="1" value="${basePrice}">
Полю со стоимость тоже добавь `required`.