Выполнила все задания в 8 модуле
htmlacademy-ecmascript/2073335-big-trip-simple-19 pull request #14
Opened 2023-02-03 12:16 UTC by Domish4

Задания выполнила вроде бы все, какие были в 8ом модуле. Внеся последние правки от тебя, могу уже идти на допуск?

2023-02-03 13:10 UTC, AlexMasterov requested changes

2023-02-03 13:10 UTC, AlexMasterov commented on src/const.js
> +  UPPER_LIMIT: 1000
const Time`Limit` = {
  LOWER_`LIMIT`: 350,
  UPPER_`LIMIT`: 1000

В названиях ключей перечисления содержат часть названия самого перечисления.

Нужно убрать.

[`Б16`](https://up.htmlacademy.ru/ecmascript/19/criteries#b16) 
> Сложные составные константы собираются в перечисления `Enum`

2023-02-03 13:10 UTC, AlexMasterov commented on src/api-service.js
> +      'date_to': new Date(point.dateTo).toISOString(),
Значением `point.dateTo` уже является объект типа `Date`:
```js
point.dateFrom instanceof Date // true
```

'date_from': `new Date(`point.dateFrom`)`.toISOString(),

Повторное создание избыточно, можно сразу использовать:

```js
point.dateTo.toISOString()
```

Нужно упростить.

2023-02-03 13:10 UTC, AlexMasterov commented on src/api-service.js
> +    delete adaptedPoint.dateTo;
Оператор `delete` плохо влияет на производительность и его использования лучше избегать.

В этом случае лучше (и проще) создать новый объект, используя показанную ранее технику:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/view/edit-form-view.js#L58

<details>
<summary>Пример</summary>

```js
#adaptToServer(point) {
  const { basePrice, dateFrom, dateTo, ...adaptedPoint } = point;

  return {
    ...adaptedPoint,
    'base_price': +basePrice,
    'date_from': dateFrom.toISOString(),
    'date_to': dateTo.toISOString(), 
  };
}
```
</details>

2023-02-03 13:10 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    if (this.points.length === 0 && this.offers.length === 0 && this.destinations.length === 0) {
🤔

См. внимательно: (названия уже исправлялись)

<details>
<summary>src</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/presenter/point-list-presenter.js#L70-L71

У модели нет `offersByType` (и хорошо!):

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/model/points-model.js#L19-L20

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/presenter/point-list-presenter.js#L74-L75

У модели нет `tripDestinations` (тоже хорошо):

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/model/points-model.js#L27-L28
</details>

При этом в других местах эти данные получаются напрямую из модели: (забывая про эти геттеры, они точно нужны?)

<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/presenter/point-list-presenter.js#L87-L88
</details>

Подобную проверку лучше вообще скрыть за методом модели:

```js
if (this.#pointsModel.isEmpty()) {
```

2023-02-03 13:10 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      this.#mode = Mode.DEFAULT;
Пожалуйста, объясни, зачем это было снова добавлено?

replace(this.#`pointFormView`, prev`PointFormView`);

Здесь заменяются вью формы и смены режима не происходит.

См.:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/9#discussion_r1067236588
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/9#discussion_r1068143017

2023-02-03 13:10 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +          <button class="event__reset-btn" type="reset">${isEdit ? deleteButtonText : 'Cancel'}</button>
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/view/edit-form-view.js#L65

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/view/edit-form-view.js#L110
</details>

В случае `isEdit` с `false` (= режим создания новой точки маршрута) переменная `deleteButtonText`, как и вычисление её значения, окажется избыточным.

Вся логика получения текста кнопок построена неудачно.

2023-02-03 13:10 UTC, AlexMasterov commented on src/view/edit-form-view.js
>              <input class="event__input  event__input--time" id="event-start-time-1" type="text" name="event-start-time" value="${humanizeDate(dateFrom, 'YY/MM/DD HH:mm')}">
См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/13#discussion_r1093301560.

> Исправлять на свое усмотрение — на защите могут не придраться

2023-02-03 13:10 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +          <button class="event__save-btn  btn  btn--blue" type="submit" ${isDisabled ? 'disabled' : ''}>${isSaving ? 'Saving...' : 'Save'}</button>
См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/13#discussion_r1093300256.

> Исправлять на свое усмотрение — на защите могут не придраться

2023-02-03 13:10 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    delete point.isDeleting;
Молодец, что не забыла удалить лишние поля.

2023-02-03 13:10 UTC, AlexMasterov commented on src/view/error-view.js
> +  return '<p class="trip-events__msg">Data connection error. Please try again later.</p>';
Под _каждое_ новое сообщение создается модуль с классом вью 🤔

См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/13#discussion_r1093265757.

2023-02-03 13:10 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/utils/filter.js#L5
</details>

> См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/13#discussion_r1093236806

См. ТЗ:
> Точки маршрута, у которых дата начала меньше текущей даты, а дата окончания — больше, отображаются во всех двух списках: `Everything` и `Future`

Нужно доработать, добавив еще одну проверку.

<details>
<summary>Еще замечания</summary>


(points) => points.filter((point) => `Date.now()`

Желательно получить _одно_ значение времени _до_ цикла, а в цикле только _переиспользоваться_. См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/8#discussion_r1065767029.

`new Date(`point.dateTo`)`.getTime()

Значение `point.dateTo` уже является объектом типа `Date` и повторное создание на его основе объект избыточно. См. другое похожие замечание.


</details>

2023-02-03 13:10 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/view/edit-form-view.js#L245
</details>

> См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/13#discussion_r1093263306

Оказалось, что обработчик с таким название обрабатывает режим кнопки с надписью `Delete`:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/src/presenter/point-presenter.js#L156-L160

Тогда оставляем, название меня немного запутало.

2023-02-03 13:10 UTC, AlexMasterov commented on src/main.js
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/4a94129991542647ec47cece80660b73a690ce2b/package.json#L38

Нужно удалить.

2023-02-03 13:10 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

```js
point-list-presenter.js:224 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAborting')
```

![image](https://user-images.githubusercontent.com/700213/216611118-b2db2241-9d12-46b5-a64b-97f2ec5962b0.png)


</details>

При удаление последней точки маршрута возникает ошибка и блокировка (зависание) страницы.

Нужно разобраться и исправить.

2023-02-03 13:10 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

```
point-list-presenter.js:156 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
```
![image](https://user-images.githubusercontent.com/700213/216611412-ac21288a-1a8c-45bf-97e4-479055c2c357.png)

</details>

При открытие приложение без данных возникает ошибка и пропало сообщения.

Нужно разобраться и исправить.

2023-02-03 13:14 UTC, AlexMasterov commented on src/const.js
> +  INIT: 'INIT'
Ключи `MAJOR` и `INIT` уже есть в `UpdateType`, а их добавление `UserAction` явно лишние.

Нужно удалить.

2023-02-03 13:16 UTC, AlexMasterov commented on src/api-service.js
> +  #adaptToServer(point) {
В методе не используется `this`.

В таком случае его можно объявить, как `static` и использоваться через `PointApiService.adaptToServer`.

2023-02-03 13:29 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/216615239-6212d0e7-e261-428d-bb62-c1646f768bfa.png)

</details>

> См. снова https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/13#discussion_r1093411861

См. внимательно ТЗ и макет.

2023-02-03 13:34 UTC, AlexMasterov commented
> Внеся последние правки от тебя, могу уже идти на допуск?

Да.

После работы смогу еще раз проверить, но вроде уже отметил всё самое важное для ТЗ и критериев.

2023-02-03 14:08 UTC, AlexMasterov commented on src/main.js
> +const AUTHORIZATION = 'Basic ap4toM49wal4pi6g';
Не забудь под конец всех правок обновить заголовок, чтобы в `master` сразу попал новый и потом на защиту отправили с чистой сессией, без доп. коммитов.

2023-02-05 14:39 UTC, Domish4 commented
Что-то как-то после дня перерыва я запуталась вообще во всем. Сейчас вроде бы все работает, убрала вообще error message, он так я понимаю и не нужен вовсе, а зачем я тогда его сделала?... столько тайн, и столько вопросов

2023-02-05 16:30 UTC, AlexMasterov requested changes

2023-02-05 16:30 UTC, AlexMasterov commented on src/model/points-model.js
> +      points.map(this.#adaptToClient);
Метод `.map` в качестве результат своей работы возвращает новый массив, но здесь он не используется, как например в другом месте:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/model/points-model.js#L37

Это действие повторяется в другом месте:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/model/points-model.js#L33

Таким образом данные с сервера запрашиваются дважды и дважды парсятся, но в первый раз, здесь, они никуда не сохраняются.

Пожалуйста, объясни, зачем это нужно?

2023-02-05 16:30 UTC, AlexMasterov commented on src/model/points-model.js
> +  #adaptToClient(point) {
<details>
<summary>model/points-model.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/model/points-model.js#L98-L111
</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/14#discussion_r1095750441

2023-02-05 16:30 UTC, AlexMasterov commented on src/const.js
> +const TimeLimit = {
Название `TimeLimit` остается непонятным в контексте модуля `const,js`.

2023-02-05 16:30 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    if (this.points.length === 0 && this.offers.length === 0 && this.destinations.length === 0) {
Не исправлено.

У презентера остаются геттеры с использованием _несуществующих_ геттеров модели:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/presenter/point-list-presenter.js#L71
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/presenter/point-list-presenter.js#L75

Но теперь сами геттеры презентера не используются.

Тогда их нужно удалить.

2023-02-05 16:30 UTC, AlexMasterov commented on src/main.js
Не исправлено.

Теперь вообще перестала правильно работать фильтрации по датам окончания.

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/utils/filter.js#L5

`point.dateTo >= point.dateFrom`

В прошлом задание была реализована валидация для ввода даты начала и окончания, которая исключает случай, когда дата окончания больше даты начала. Такая проверка не нужна.

См. ТЗ:
> Future — список запланированных точек маршрута, т. е. точек, у которых:

> **дата начала меньше текущей даты, а дата окончания — больше** (не было сделано)
> дата начала события больше или равна текущей дате (было сделано, но теперь удалено)

Нужно разобраться и доработать два условия.

2023-02-05 16:30 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    if (this.points.length === 0 && !this.#isLoading) {
if (this.points.length === 0 && `!this.#isLoading`) {

Выражение всегда будет возвращать `false`, потому что при `this.#isLoading` с `true` до этой проверки просто не дойдет, сработает другая с выходом из функции:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/presenter/point-list-presenter.js#L151-L153

2023-02-05 16:30 UTC, AlexMasterov commented on src/const.js
Если удалить все созданные точки маршрута и не обновляя страницу открыть форму создания новой точки маршрута, то после её закрытия (без создания) не появляется сообщение об отсутствие точек маршрута.

См. ТЗ:
> В случае отсутствия точек маршрута вместо списка отображается текст: «Click New Event to create your first point»

Нужно исправить.

2023-02-05 16:30 UTC, AlexMasterov commented on src/const.js
Если удалить все созданные точки маршрута и обновить страницу, сохранив сессию, то в отсутствие точек маршрута не появляется форма для создания новой точки, хотя кнопка для создания неактивна.

Нужно исправить.

2023-02-05 17:36 UTC, AlexMasterov commented on src/const.js
См. ТЗ:
> Если в отфильтрованном списке были удалены все точки маршрута, вместо списка отображается соответствующий текст. Например, если пользователь удалил все точки маршрута из списка Future, вместо списка должна появиться заглушка «There are no future events now». Все фразы приведены в файле в директории с разметкой

Фильтрация перестала работать и не получается проверить этот пункт.

После исправления фильтрации проверь самостоятельно.

2023-02-06 11:16 UTC, AlexMasterov requested changes
Осталась последняя проблема.

2023-02-06 11:16 UTC, AlexMasterov commented on src/const.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/216949780-e7f949c1-e35f-470f-8b08-859f131c8607.png)

![image](https://user-images.githubusercontent.com/700213/216949634-10351be2-44b4-4f67-af61-251b862de507.png)

</details>

После открытия формы создания новой точки маршрута в непустом списке появляется неуместный текст.

Нужно исправить.

2023-02-06 11:16 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    const pointsCount = points.length;
<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/presenter/point-list-presenter.js#L132-L137
</details>

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/14#discussion_r1096733084

В случае `this.#isLoading` с `true` выполнение функции прервется и получение выше (их фильтрация, сортировка) данных с точками маршрута окажутся избыточным.

2023-02-06 11:16 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    if (!pointsCount && !this.#pointsModel.offers.length && !this.#pointsModel.destinations.length) {
<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/presenter/point-list-presenter.js#L140
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/presenter/point-list-presenter.js#L145
</details>

После большого кол. замечаний снова используется неявное приведение 😟

<details>
<summary>presenter/point-list-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/presenter/point-list-presenter.js#L140
</details>

См. также https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/14#discussion_r1095754625:

> Подобную проверку лучше вообще скрыть за методом модели:

```js
if (this.#pointsModel.isEmpty()) {
```

2023-02-06 11:16 UTC, AlexMasterov commented on src/utils/filter.js
> +  [FilterType.FUTURE]: (points) => points.filter((point) => isPointFuture(point.dateFrom) || isPointFuture(point.dateTo)),
<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/utils/filter.js#L4-L6
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/utils/filter.js#L10
</details>

Изначально, до исправлений, выполнялось второе условие, а реализация была значительно быстрее. Сейчас проверки дублируются, но работает по ТЗ 😃

> \+ осталась критическая проблема с получением значение даты на _каждой_ итерации цикла. Только теперь вместо одного числового значения времени создаются по два объекта `dayjs`, что в 9 раз медленнее

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/8#discussion_r1065767029.

<details>
<summary>Покажи, что ожидалось </summary>

```js
[FilterType.FUTURE]: (points, dateNow = Date.now()) => points.filter(({ dateFrom, dateTo }) =>
    dateFrom.getTime() >= dateNow ||
    (dateFrom.getTime() < dateNow && dateTo.getTime() > dateNow)
)
```

В таком решение в цикле используется только _одно_ значение времени, которое берется из параметра. `Date.now()` в 6-7 раз быстрее создание объекта `Date` и в 9 раз быстрее создания объекта `dayjs`.
</details>

2023-02-06 11:17 UTC, AlexMasterov commented on src/main.js
> +const AUTHORIZATION = 'Basic ap4toM49wal4pi6g';
Актуально.

2023-02-06 11:19 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/216958467-fc367a17-7aeb-48fa-a2e0-baa252393505.png)

</details>

Если открыть форму редактирования и не закрывая, открыть форму создания, то на `document` остается обработчик для `keydown` от формы редактирования.

[`Б36`](https://up.htmlacademy.ru/ecmascript/19/criteries#b36) 
> Обработчики события добавляются и удаляются своевременно

2023-02-06 11:42 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/0a1b0f43e56c094c91d1bdf850abc765d356678e/src/view/edit-form-view.js#L184
</details>

.addEventListener(`'input'`, this.#price`Input`Handler);

Лучше отслеживать `change`.

2023-02-06 12:39 UTC, Domish4 commented
По моим ощущениям неопытного человека, я перепробовала все, что можно, чтобы сообщение об отсутствии точек отображалось корректно. Щас если лезть в верстку она чуть криво стоит (после trip events list, но в контейнере trip events), но на глаз ок. Это зло, с которым кажется придется смириться, если только это не заметит человек на защите....
`if (this.#pointsModel.isEmpty()) ` не работает у меня( грит это не функция и все, может я опять туплю. 
Обработчики вроде поправила, сделав `{once: true}`

2023-02-06 12:58 UTC, AlexMasterov requested changes

2023-02-06 12:58 UTC, AlexMasterov commented on src/model/points-model.js
Если открыть форму редактирования или создания точки маршрута и нажать на любую клавишу кроме `Esc`, то перестает работать закрытие формы по `Esc`.

Нужно разобраться и исправить.

2023-02-06 12:58 UTC, AlexMasterov commented on src/model/points-model.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/216975330-f39029ca-e58d-4edb-91eb-e45a2a0a0285.png)
![image](https://user-images.githubusercontent.com/700213/216975703-9a1b3790-eb2d-4556-8fca-4856d99a9264.png)

![image](https://user-images.githubusercontent.com/700213/216976034-679649a5-653d-4817-b386-56e0dd66ccfd.png)

</details>

<details>
<summary>Видео</summary>

[2073335-issue-save.webm](https://user-images.githubusercontent.com/700213/216977232-09b4d153-68e6-4eb7-af12-d18a76434c73.webm)

</details>

Перестало работать сохранение точки маршрута.

2023-02-06 12:59 UTC, AlexMasterov commented on src/main.js
Не исправлено, но добавилась новая проблема, см. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/14#discussion_r1097330898.

2023-02-06 13:15 UTC, AlexMasterov commented on src/model/points-model.js
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/d9a37605f31ec19296c9d6f80450f5a0fae18b65/src/presenter/point-presenter.js#L150

Это лишние и нужно удалить.

2023-02-06 13:21 UTC, AlexMasterov commented on src/model/points-model.js
<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/d9a37605f31ec19296c9d6f80450f5a0fae18b65/src/presenter/point-list-presenter.js#L174
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/d9a37605f31ec19296c9d6f80450f5a0fae18b65/src/presenter/point-presenter.js#L30
</details>

2023-02-06 13:40 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +    if (!pointsCount && !this.#pointsModel.offers.length && !this.#pointsModel.destinations.length) {
> if (this.#pointsModel.isEmpty())  не работает у меня( грит это не функция и все, может я опять туплю.

В качестве примера показал вариант (ожидание) по интерфейсу метода, который мог бы выполнять эту проверку, а реализовать его в модели нужно самой.

2023-02-06 14:09 UTC, Domish4 commented on src/model/points-model.js
это из-за этого были проблемы с сохранением точки маршрута? просто я переделала  #handleSubmitForm в поинт презентере и вроде бы все починилось.

2023-02-06 14:19 UTC, AlexMasterov commented on src/const.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/216993669-26dca05b-68ea-4f0a-b1e7-0f43ae480a24.png)

</details>

<details>
<summary>Ожидание (markup/list-empty.html)</summary>

![image](https://user-images.githubusercontent.com/700213/216993843-2c95e9a9-df81-4134-83eb-cad6f2acc2ab.png)

</details>


Не очень понимаю, в чем проблема добавить сообщение в узел списка, а не в общий контейнер.

> Это зло, с которым кажется придется смириться

Наверное, даже [нашел куб в тему](https://coub.com/view/340gzy) 😃

https://user-images.githubusercontent.com/700213/216992759-ed385e77-eec6-4655-b656-d96bacfe1632.mp4

2023-02-06 14:23 UTC, AlexMasterov commented on src/model/points-model.js
Выше показал, что проблема здесь:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/d9a37605f31ec19296c9d6f80450f5a0fae18b65/src/presenter/point-list-presenter.js#L174

Если не менять интерфейс, то должно быть как здесь:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/d9a37605f31ec19296c9d6f80450f5a0fae18b65/src/presenter/point-list-presenter.js#L91-L95

Вот так:

```js
this.#pointPresenters.get(point.id).init({
  point, 
  tripDestinations: this.#pointsModel.destinations, 
  allOffers: this.#pointsModel.offers, 
});
```

2023-02-06 14:31 UTC, AlexMasterov commented
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/216993669-26dca05b-68ea-4f0a-b1e7-0f43ae480a24.png)

</details>

<details>
<summary>Ожидание (markup/list-empty.html)</summary>

![image](https://user-images.githubusercontent.com/700213/216993843-2c95e9a9-df81-4134-83eb-cad6f2acc2ab.png)

</details>

> Щас если лезть в верстку она чуть криво стоит (после trip events list, но в контейнере trip events), но на глаз ок. Это зло, с которым кажется придется смириться

Для защиты главное, чтобы сама страница отображалась, как показано в макете. Пустой узел с списком в DOM на это не влияет и всё нормально 😃

2023-02-06 14:35 UTC, AlexMasterov commented on src/model/points-model.js
> просто я переделала #handleSubmitForm в поинт презентере и вроде бы все починилось

В `#handleSubmitForm` достаточно учесть https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/14#discussion_r1097363162

2023-02-06 14:43 UTC, AlexMasterov commented on src/model/points-model.js
Нашел [куб](https://coub.com/view/340gzy), что пора на отдых 😃

https://user-images.githubusercontent.com/700213/216992759-ed385e77-eec6-4655-b656-d96bacfe1632.mp4

2023-02-06 15:19 UTC, AlexMasterov commented on src/main.js
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6df65c5d2c45c56129658d81487a96d38fa2874c/src/presenter/point-presenter.js#L123

Нужно вернуть, как было, убрав `{ once: true }`.

2023-02-06 15:20 UTC, AlexMasterov commented on src/main.js
Для исправления самым простым будет добавить удаление обработчика в метод `destroy()`:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6df65c5d2c45c56129658d81487a96d38fa2874c/src/presenter/point-presenter.js#L71-L73

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6df65c5d2c45c56129658d81487a96d38fa2874c/src/presenter/point-presenter.js#L131

2023-02-06 15:21 UTC, AlexMasterov commented on src/main.js
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6df65c5d2c45c56129658d81487a96d38fa2874c/src/presenter/point-presenter.js#L168-L169

Удаление обработчика уже происходит в `#replaceFormToCard()`, а здесь будет повторяться.

Нужно удалить.

2023-02-06 15:26 UTC, AlexMasterov commented
Нужно исправить последнею проблему с накоплением обработчиков.

См. вариант решения https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/14#discussion_r1097526013.

2023-02-06 15:31 UTC, AlexMasterov commented on src/presenter/point-list-presenter.js
> +  renderNoPoint () {
Нужно сделать приватным.

2023-02-06 16:39 UTC, AlexMasterov commented
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/1#issuecomment-1339005762

[Приключение на 20 минут...](https://www.youtube.com/watch?v=8iquKv_Ha5A#t=25s) 😃

2023-02-06 16:39 UTC, merged