1.11. Время разбивать камни
htmlacademy-ecmascript/2073335-big-trip-simple-19 pull request #3
Opened 2022-12-09 09:13 UTC by Domish4

2022-12-09 13:08 UTC, AlexMasterov requested changes

2022-12-09 13:08 UTC, AlexMasterov commented on src/view/creation-form-view.js
> +export default class NewFormView {
view/`creation-form-view`.js !== `NewFormView`

[`Б 27`](https://up.htmlacademy.ru/ecmascript/19/criteries#b27)
> Название модуля соответствует его содержимому

> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2022-12-09 13:08 UTC, AlexMasterov commented on src/main.js
> +const bodyElement = document.querySelector('.page-body');
Избыточно и можно удалить.

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +  boardComponent = new WaypointListView();
`boardComponent` = new `WaypointListView`();

По названию свойства нельзя понять, на какой экземпляр класса (объект) оно указывает, что может сильно запутать.

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +  constructor({boardContainer}) {
<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/src/presenter/board-presenter.js#L9
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/src/presenter/board-presenter.js#L12-L13
</details>


Название основного элемента-контейнера можно упростить:
```diff
- constructor({boardContainer}) {
+ constructor({container}) {
```
Если будет изменено название класса, то не придется менять название параметра.

> Если в классе появится еще один контейнер, то уже его имя можно уточнить

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    render(new EditFormView(), this.boardComponent.getElement(), 'afterbegin');
render(new EditFormView(), this.boardComponent.getElement(), `'afterbegin'`)

Нужно использовать значение из перечисления `RenderPosition.AFTERBEGIN`:
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/src/render.js#L3

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/206705923-8d600db7-df16-44e9-9998-0da009393ef5.png)

</details>

Это форма _создания_ точки маршрута. 

> См. макет. Разметка _режимов_ форм отличается только наличием "крышки" для сворачивания и названием одной кнопки. Из-за этого не стоит дублировать 99% разметки

См. задание:
> компонент «**Форма редактирования**» отрисовывается 1 раз, но должен располагаться первым в списке

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/206706171-aa445699-4e9f-4e0e-ba2d-373e6b5f61a8.png)

</details>

См. задание:
> компонент «Форма редактирования» **отрисовывается 1 раз**, но должен располагаться первым в списке

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/206706422-b14478ff-bd9a-4706-94c4-0c63b78c2141.png)

</details>

См. задание:
> компонент «Точка маршрута» **отрисовывается в списке 3 раза**

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/206706781-126db198-5db7-4b4a-aeac-66b9fee87019.png)

</details>

<details>
<summary>Ожидание (markup/list.html)</summary>

![image](https://user-images.githubusercontent.com/700213/206707014-c5e0f527-382b-4a3f-8bee-e763bba519f8.png)

</details>

Текущий порядок узлов не совпадает с макетом.

Нужно разобраться и исправить.

2022-12-09 13:08 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>public/index.html</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/public/index.html#L32
</details>

Для этой разметки желательно тоже создать компонент.

> После создания компонента нужно не забыть удалить её разметку из `index.html`

2022-12-09 13:08 UTC, AlexMasterov commented on src/main.js
> +const sortElement = bodyElement.querySelector('.trip-events');
const `sortElement` = bodyElement.querySelector(`'.trip-events'`);

"Легким движением клавиш"... узел с классом `'.trip-events'` превращается в `sort` 🤔

2022-12-09 13:08 UTC, AlexMasterov commented on src/view/waypoint-list-view.js
> +  `<ul class="trip-events__list">
Компонент с таким названием должен создавать только _пустую_ разметку одного этого узла `trip-events__list`.

См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-1/src/view/board-view.js#L4).

2022-12-09 13:08 UTC, AlexMasterov commented on src/view/waypoint-list-view.js
> +  <li class="trip-events__item">
Для создания разметки `trip-events__item` нужно использовать отдельный компонент.

2022-12-09 13:08 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>markup/list-empty.html</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/markup/list-empty.html#L54-L61
</details>

<details>
<summary>markup/loading.html</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/markup/loading.html#L54
</details>

Советую для этой разметки сразу создать отдельный компонент(ы).

> Обрати внимание, что разметка отличается только сообщением

2022-12-09 13:08 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    render(this.boardComponent, this.boardContainer);
<details>
<summary>presenter/board-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/53b269685e081c377fe010a5d54ae0ed4e702b9b/src/presenter/board-presenter.js#L18-L24
</details>

`this.boardContainer` указывает на элемент, который добавлен в DOM и в нем отображается.

Советую выполнить такой рендер _после_ цикла, когда уже все элементы будет готовы.

[`Б 35`](https://up.htmlacademy.ru/ecmascript/19/criteries#b35)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

> Этот критерий уже много лет не соблюдается~

2022-12-09 13:09 UTC, AlexMasterov commented on src/view/creation-form-view.js
> +const createNewFormTemplate = () => (
С учетом нахождения таких функций в модуле с компонентом их название можно упростить:

```diff
- function createNewFormTemplate() {
+ function createTemplate() {
```

2022-12-12 10:38 UTC, Domish4 commented on src/presenter/board-presenter.js
> +  constructor({boardContainer}) {
Чего-то у меня оно так не работает( все сразу ломается...

2022-12-12 17:03 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +  constructor({boardContainer}) {
Чтобы это заработало нужно так же изменить название свойства объекта, который передается в конструктор `BoardPresenter` в качестве аргумента:

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/main.js#L11
</details>

```diff
- const boardPresenter = new BoardPresenter({boardContainer: tripEventsElement});
+ const boardPresenter = new BoardPresenter({container: tripEventsElement});
```

<details>
<summary>presenter/board-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/presenter/board-presenter.js#L11-L13
</details>

```js
constructor({ container }) {
  this.container = container;
}
```

2022-12-12 17:45 UTC, AlexMasterov requested changes
К сожалению, нужно еще немного доработать. Уже намного лучше.

Пожалуйста, сверяйся с макетом до отправки на повторную проверку.

2022-12-12 17:45 UTC, AlexMasterov commented on src/main.js
> +//import FiltersView from './view/filter-view.js';
Нужно удалить.

[`Б 18`](https://up.htmlacademy.ru/ecmascript/19/criteries#b18)
> В коде проекта нет файлов и частей кода, которые не используются, **включая закомментированные участки кода**

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/button-view.js
> +export default class ButtonView {
Желательно уточнить, что за кнопка:
```diff
- export default class ButtonView {
+ export default class NewEventButtonView {
```
> В случае исправления нужно также не забыть изменить название модуля: `view/button-view.js` (см. [`Б27`](https://up.htmlacademy.ru/ecmascript/19/criteries#b27)) + [import в main.js](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/main.js#L6)

2022-12-12 17:45 UTC, AlexMasterov commented on src/main.js
> +render(new SortView(), tripEventsElement);
Советую перенести в `BoardPresenter` и пока работать с сортировкой там, как это показано в демо проекте.

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/empty-list-view.js
> +<p class="trip-events__msg">Click New Event to create your first point</p>
См.:

<details>
<summary>public/index.html</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/public/index.html#L38-L44
</details>

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/main.js#L9
</details>

Секцией `trip-events` находится в `index.html` и DOM-элемент на этот узел используется как контейнер. Если потребуется с помощью этого компонента вывести сообщение, то произойдет дублирование секции, что скорее всего сломает разметку.

См. внимательно https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044433751:

<details>
<summary>разметка</summary>

![image](https://user-images.githubusercontent.com/700213/207110320-3afcbef8-d1c5-4c41-a384-5cbb06e09096.png)

</details>

Нужно было забрать только разметку для сообщения:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/view/empty-list-view.js#L7

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/empty-list-view.js
> +<p class="trip-events__msg">Click New Event to create your first point</p>
<details>
<summary>view/empty-list-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/view/empty-list-view.js#L7
</details>
<details>
<summary>view/loading-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/view/loading-view.js#L7
</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044433751:
> Обрати внимание, что разметка отличается только сообщением

Вместо того, чтобы создавать отдельные компоненты под каждое сообщение, можно один универсальный  компонент, например, `TripMessage`, который мог бы принимать в качестве аргумент любое сообщение.

> Не критично

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/loading-view.js
> +          <p class="trip-events__msg">Loading...</p>
Для этого компонента нужно оставить только разметку с сообщением.

2022-12-12 17:45 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +  boardComponent = new TripEventsListView();
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044420941.

```diff
- boardComponent = new TripEventsListView();
+ tripEventsListView = new TripEventsListView();
```

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  `<li class="trip-events__item">
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044433176.

В этом компоненте нужно оставить только разметку с _одним_ `trip-events__item`, как показано в замечание (и в демо проекте):

<details>
<summary>view/trip-events-item-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/view/trip-events-item-view.js#L4-L31
</details>

2022-12-12 17:45 UTC, AlexMasterov commented on src/main.js
> +const tripControlsFiltersElement = document.querySelector('.trip-controls__filters');
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/207112941-151e8f60-0f46-4a37-b5f8-e8e9ec3018d4.png)

</details>

<details>
<summary>view/filter-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/view/filter-view.js#L4
</details>

Узел `.trip-controls__filter` есть в `index.html` и создается (дублируется) в разметки компонента.

В этом случае чтобы избежать дублирование и несоответствия макету. нужно удалить его из `index.html`:

<details>
<summary>public/index.html</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/public/index.html#L26-L29
</details>

или удалить эту разметку из самого компонента, оставив только форму:

<details>
<summary>view/filter-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/6d43fbe221bfebf94f82eee1e4903e4f42a50211/src/view/filter-view.js#L6-L18
</details>

Нужно исправить.

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +export default class EditFormView {
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/207114581-3c1ced9a-8e62-4baf-931a-787add84bf59.png)

</details>

<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/207114712-a97fec6b-4113-4ff2-8c0b-939452c5c676.png)

</details>

Сейчас форма добавлена прямо в список `<ul>`.

Нужно обернуть форму в `<li>` с `.trip-events__item`, как было показано в замечание (и макете).

2022-12-12 17:45 UTC, AlexMasterov commented on src/view/form-view.js
> +  <form class="event event--edit" action="#" method="post">
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044422469.

Разметка компонента `FormView` на 99% дублирует `EditFormView`.

Нужно удалить и вместо него использовать `EditFormView`.

2022-12-12 17:45 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/207115637-3aefe2b8-9a3c-481f-98e6-3beea64161e6.png)

</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044424553.

Не исправлено.

2022-12-13 15:28 UTC, AlexMasterov commented on src/view/trip-events-view.js
> +const createTemplate = () => ('<section class="trip-events"><h2 class="visually-hidden">Trip events</h2></section>');
В таком использование `()` нет смысла.

Для сохранения отступа начала и конца разметки нужно правильно использовать `()`:
```js
const createTemplate = () => (
  '<section class="trip-events">
    <h2 class="visually-hidden">Trip events</h2>
  </section>'
);
```
> Так же важно помнить, что шаблонный строки сохраняют пробелы и переводы строки. На основе разметки с пустой строкой в начале будет создан узел типа `#text` (а не `Element`), который нам не нужен. Желательно этого не допускать. См. [пример проблемы](https://developer.mozilla.org/ru/docs/Web/API/Node/firstChild#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80)

2022-12-13 15:29 UTC, AlexMasterov commented
👍🏻

2022-12-13 15:30 UTC, merged