Module2 task1
htmlacademy-ecmascript/2073335-big-trip-simple-19 pull request #4
Opened 2022-12-16 12:46 UTC by Domish4

JS1 был детским садом, а это, я так понимаю, ад

2022-12-17 02:21 UTC, AlexMasterov requested changes

2022-12-17 02:21 UTC, AlexMasterov commented on src/main.js
>  render(new FilterView(), tripControlsFiltersElement);
Для _будущей_ работы с фильтром (`FilterView`) следует создать презентер.

2022-12-17 02:21 UTC, AlexMasterov commented on src/mock/mock.js
> +    id: 0,
В ТЗ `id` в структуре `Point` задано _строкой_, а здесь используется _число_.

<details>
<summary>ТЗ: Point</summary>

![image](https://user-images.githubusercontent.com/700213/208216559-f7093e11-1bb8-4d4e-b4a3-ab70c5f97749.png)

</details>

2022-12-17 02:21 UTC, AlexMasterov commented on src/mock/mock.js
> +    dateTo: '2019-07-12T11:25:13.375Z'
Даты из строк формата ISO следует сразу _парсить_, превращая в специальные объекты, например, `Date`, чтобы уже внутри приложения работать с ними.

См. [пример демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-3/src/mock/task.js#L39).

2022-12-17 02:21 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    this.listPoints = [...this.pointsModel.getPoints()];
this.`list`Point`s` = [...this.pointsModel.getPoints()];

В название масло масленое. 

Чтобы название переменной указывало на базовую структуру `Array` вполне достаточно  использовать множественное число, добавляя `s`.

2022-12-17 02:21 UTC, AlexMasterov commented on src/util.js
> +function humanizeEventDueDate(dueDate, dateFormat) {
function humanizeEvent`Due`Date(`due`Date, dateFormat) {

Не могу найти в ТЗ проекта "Большое путешествие" упоминание про `dueDate` 😃

2022-12-17 02:21 UTC, AlexMasterov commented on src/util.js
> +const getRandomArrayElement = (items) => items[Math.floor(Math.random() * items.length)];
```diff
- const getRandomArrayElement = (items) => items[Math.floor(Math.random() * items.length)];
+ const getRandomArrayItem = (items) => items[Math.floor(Math.random() * items.length)];
```

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const offersList = () => {
const `offersList` = () => {

<details>
<summary>view/trip-events-item-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/trip-events-item-view.js#L57
</details>

[`Б 10`](https://up.htmlacademy.ru/ecmascript/19/criteries#b10) 
> Название функции или метода содержит глагол [в начале]

<details>
<summary>Пример</summary>

```diff
- const offersList = () => {
+ const createOffersListTemplate = () => {
```
</details>

2022-12-17 02:21 UTC, AlexMasterov commented on src/main.js
<details>
<summary>src</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/edit-form-view.js#L5
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/filter-view.js#L3
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/loading-view.js#L3
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/new-event-button-view.js#L3
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/sort-view.js#L3
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/trip-events-item-view.js#L5
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/trip-events-item-view.js#L19
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/trip-events-list-view.js#L3
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/trip-events-view.js#L3
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/util.js#L7
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/util.js#L9
</details>

const createTemplate = (point) `=>` { 
**и т.п.**

[`Д 5`](https://up.htmlacademy.ru/ecmascript/19/criteries#d5) (Обновлён 09.12.22)
> по умолчанию используется _декларативное_ объявление функций

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const createTripTypeTemplate = offersByTypes.map((item) =>
const `create`TripTypeTemplate = offersByTypes.map((item) =>

<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/edit-form-view.js#L46
</details>

Переменная указывает на _строку_, а не _функцию_.

Нужно из названия убрать _глагол_.

[`Б 4`](https://up.htmlacademy.ru/ecmascript/19/criteries#b4)
> Для названия значений используются английские _существительные_

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const createOffersTemplate = offerByType.offers.map((offer) =>
const `create`OffersTemplate = offerByType.offers.map((offer) =>

Это тоже не функция.

[`Б 4`](https://up.htmlacademy.ru/ecmascript/19/criteries#b4)
> Для названия значений используются английские _существительные_

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      <input id="event-type-${item.type}-${item.offers.id}" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${item.type}" ${item.type.isChecked ? 'checked' : ''}">
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/208218845-c9980e3c-3c7c-4aae-85a5-316589c05b94.png)

</details>

<details>
<summary>Ожидание (markup)</summary>

![image](https://user-images.githubusercontent.com/700213/208219452-2f096bdc-655d-4a25-a98e-a460cfcd8d27.png)

</details>

Вывод выбранного в данных типа работает неправильно.

Нужно разобраться и исправить.

<details>
<summary>hint</summary>

item.type.`isChecked` ? 'checked' : ''}

```js
typeof item.type // string
typeof item.type.isChecked // undefined
```
`item.type` указывает на _строку_ с название типа. У строки нет свойства item.type.`isChecked`.
</details>

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const cities = destinations.map((item) => `<option value="${item.name}"></option>`).join('');
`cities` указывает на _строку_ с шаблон разметкой `<option>`.

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +    .filter((offer) => offers.includes(offer.id));
const `offersChecked` = pointOffersType.offers.filter((offer) => offers.includes(offer.id));

> `.filter` возвращает [новый] _массив_

```js
Array.isArray(offersChecked) // true
```

[`Б 8`](https://up.htmlacademy.ru/ecmascript/19/criteries#b8)
> Массивы названы существительными во множественном числе

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +    if (!offersChecked.length) {
Как начинающий старайся [пока] меньше использовать _неявное_ приведение типов:

```diff
- if (!offersChecked.length) {
+ if (offersChecked.length === 0) {
```

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +    } else {
<details>
<summary>view/trip-events-item-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/28f77bc8f787fba6ab8f4e4da009316934714201/src/view/trip-events-item-view.js#L20-L26
</details>

`if + return + else`

В таком условие можно убрать `else`.

[`Д 12`](https://up.htmlacademy.ru/ecmascript/19/criteries#d12) 
> Если при использовании условного оператора в любом случае возвращается значение, альтернативная ветка опускается

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +import { destinations, offersByTypes } from '../mock/mock.js';
См. задание:
> Исправьте `View` точки маршрута так, **чтобы контент ожидался снаружи компонента.**

Не должно быть прямой работы с _временным_ модулем `mock`. Компоненты `view` должны работать с данными, как с настоящими. Данные (или возможность доступа к ним) следует передавать через аргументы конструктора, как показано в примере демо проекта.

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/208218870-e85ecdc6-20e6-4ed0-8f09-8a6b8650483f.png)

</details>

<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/208218889-f30aafe8-8ba4-4544-bf3f-115d904df54e.png)

</details>

Нужно из макета добавить в форму разметку с секцией изображений и вывести в ней данные.

2022-12-17 02:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +
<details>
<summary>Проблема</summary>

```js
{
  'type': 'taxi',
  'offers': []
},
```


![image](https://user-images.githubusercontent.com/700213/208218994-0d142c23-9153-4394-8003-7b351ad9097a.png)

</details>

См. ТЗ:
> Список дополнительных опций доступен не для всех типов точек маршрута. Для некоторых типов точек дополнительные опции могут отсутствовать. **В этом случае контейнер для вывода дополнительных опций не отображается**

2022-12-17 02:28 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const offersList = () => {
Советую создать функцию за пределами `createTemplate`, один раз, и только переиспользовать внутри. Все нужные данные можно передавать через аргументы.

> Актуально для других вложенных функций и просто кода, который создает шаблон с разметкой. Компоненты используются часто

2022-12-17 03:58 UTC, AlexMasterov commented on src/main.js
См. задание:
> Обратите внимание, если у вас форма редактирования выступает и в роли формы создания — вы решили обойтись одним компонентом, как в демо-проекте — **нужно предусмотреть, чтобы шаблон корректно отображался с «пустыми» данными**

2022-12-17 04:07 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      <label class="event__type-label  event__type-label--${item.type}" for="event-type-${item.type}-${item.offers.id}">${item.type}</label>
```js
item.offers.id // undefined
``
🤔

2022-12-17 04:14 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.point = point;
this.`point` = point;

[`Б 17`](https://up.htmlacademy.ru/ecmascript/19/criteries#b17) 
> Приватные и защищённые поля в классах помечены и не используются снаружи

**Актуально для всего проекта.**

> См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-3/src/presenter/board-presenter.js#L24-L25)

2022-12-17 04:17 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const timeEndInDateTime = humanizeEventDueDate(dateTo, 'YYYY-MM-DDTHH:mm');
humanizeEventDueDate(dateFrom, `'MMM DD'`)
и т.п.

[`Б 5`](https://up.htmlacademy.ru/ecmascript/19/criteries#b5) 
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

На защите проекта _могут_ придраться.

> См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-3/src/utils.js#L3)

2022-12-17 08:44 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      <input id="event-type-${item.type}-${item.offers.id}" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${item.type}" ${item.type.isChecked ? 'checked' : ''}">
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/208218845-c9980e3c-3c7c-4aae-85a5-316589c05b94.png)

</details>

<details>
<summary>Ожидание (markup)</summary>

![image](https://user-images.githubusercontent.com/700213/208219452-2f096bdc-655d-4a25-a98e-a460cfcd8d27.png)

</details>

В макете названия типов отображаются с большой буквы.

2022-12-20 12:59 UTC, AlexMasterov commented on src/presenter/board-presenter.js
>    TripEventsListView = new TripEventsListView();
`T`ripEventsView = new TripEventsView();
`T`ripEventsListView = new TripEventsListView();

[`Б 3`](https://up.htmlacademy.ru/ecmascript/19/criteries#b3) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации [`camelCase`](https://ru.wikipedia.org/wiki/CamelCase)

2022-12-20 20:37 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    this.point = point;
Пока можно отложить.

2022-12-21 13:36 UTC, Domish4 commented on src/main.js
Я не понимаю это, насчет шаблона вроде бы предусмотрела, а вот то что ты сказал про поинт и локалпоинт я не понимаю...

2022-12-21 13:38 UTC, Domish4 commented on src/view/edit-form-view.js
> +
Я это вижу так: поставить условие в контейтер по офферам, offersTemplate.length > 0 ? offersTemplate : createsomething(), где createsomething это функция которая либо прячет либо удаляет контейтер с офферами. Но у меня не получилось))

2022-12-21 14:51 UTC, Domish4 commented on src/view/edit-form-view.js
> +
Ой, вроде бы сделала!

2022-12-21 15:50 UTC, AlexMasterov requested changes
К сожалению, нужно доработать.

2022-12-21 15:50 UTC, AlexMasterov commented on src/util.js
> +function capitalize(str) {
function capitalize(`str`) {

[`Б 4`](https://up.htmlacademy.ru/ecmascript/19/criteries#b4)
> Сокращения в словах запрещены

[`Б 9`](https://up.htmlacademy.ru/ecmascript/19/criteries#b9) 
> В названии переменных не используется тип данных

<details>
<summary>Пример</summary>

```js
function capitalize(text) {
  return text.charAt(0).toUpperCase().concat(text.slice(1));
}
```
</details>

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const citiesStringTemplate = tripDestinations.map((item) => `<option value="${item.name}"></option>`).join('');
const cities`String`Template

[`Б 9`](https://up.htmlacademy.ru/ecmascript/19/criteries#b9) 
> В названии переменных не используется тип данных (= `string`)

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/empty-list-view.js
> +  return ('<p class="trip-events__msg">Click New Event to create your first point</p>'
return `(`'

В таком использование `()` нет смысла.

См. подробней https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1047313910.

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/loading-view.js
> +}
```js
createTemplate() // undefined
```
Такая функция ничего не возвращает (= `undefined)`.

Нужно возвращать строку с разметкой явно, с помощью `return`.

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/trip-controls-filters-view.js
> +
Нужно удалить из разметки пустую строку.

См. подробней https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1047313910.

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/trip-main-view.js
> +
Нужно удалить из разметки пустую строку.

См. подробней https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1047313910.

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const createoffersList = () => {
<details>
<summary>createoffersList </summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/c4b6b41069fd3d06ec51769725baa7efda74d10f/src/view/trip-events-item-view.js#L20-L36
</details>

`createo`ffersList 

[`Б 3`](https://up.htmlacademy.ru/ecmascript/19/criteries#b3) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации [`camelCase`](https://ru.wikipedia.org/wiki/CamelCase)

Функция создает шаблон с разметкой, но это всё еще плохо выражено в её название.

[`Б 10`](https://up.htmlacademy.ru/ecmascript/19/criteries#b10)
> Название функции или метода должно быть глаголом и **соответствовать действию**, которое выполняет функция или метод

См. [пример исправления в замечание](https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1051285240).

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +    const checkedOffersTemplate = checkedOffers.map((offer) =>
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/c4b6b41069fd3d06ec51769725baa7efda74d10f/src/view/trip-events-item-view.js#L34

Можно сразу возвращать результат `.map` + `.join`, без создания временной переменной:

```diff
- const checkedOffersTemplate = checkedOffers.map((offer) =>
+ return checkedOffers.map((offer) =>
```
> В таком случае не нужно придумывать переменной название 😃

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const TIME = {
<details>
<summary>view/trip-events-item-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/c4b6b41069fd3d06ec51769725baa7efda74d10f/src/view/trip-events-item-view.js#L8-L14
</details>

const `TIME` = {

Константы следует создавать вне функции, а вычисление их значений должно исключать [побочные эффекты](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B1%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), нечистые функции с получением времени и т.п.

> Не очень понятно, что это и зачем, вероятно, замечание было понято неверно. Подобное именование формально нарушает критерий \+ `TIME` чего? слишком общие название

[`Б 3`](https://up.htmlacademy.ru/ecmascript/19/criteries#b3) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации [`camelCase`](https://ru.wikipedia.org/wiki/CamelCase)

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const TIME = {
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/view/edit-form-view.js#L18-L21
</details>

const `TIME` = {

[`Б 3`](https://up.htmlacademy.ru/ecmascript/19/criteries#b3) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации [`camelCase`](https://ru.wikipedia.org/wiki/CamelCase)

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  basePrice: '',
В структуре `Point` значение `basePrice` задано _числом_:

```diff
- basePrice: '',
+ basePrice: 0,
```
> Можно использовать `0`, как "значение по умолчанию", "отсутствие (актуального) значения"

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  destination: '',
Желательно "отсутствие (актуального) значения" задать в рамках одного типа или использовать `null`.

Нужно выбрать между:
```diff
- destination: '',
+ destination: 0,
```
или
```diff
- destination: '',
+ destination: null,
```

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  id: 0,
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1051307003:
> в структуре данных `LocalPoint` нет `id`

`id` создается на сервере, а в созданном на клиенте `LocalPoint` его нет:

```diff
- id: 0,
```

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +const EMPTY_POINT = {
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/view/edit-form-view.js#L4
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/view/edit-form-view.js#L6-L7
</details>

Получение даты требует обращения к ОС, что считается [побочным эффектом](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B1%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), а сами даты будут изменяться при каждом запуске приложения. 

> В Академии пока нет договорённости насчет именования статичных (`static`) значений, которые можно вычислить "во время выполнения", но при этом записать в константу.

Если хочешь сохранить название переменной с объектом в формате константы, то его свойствам `dateFrom`, `dateTo` в качестве значения следует указать `null`. 

Если хочешь сохранить даты, то переименую в `camelCase` или просто создавай объект с помощью функции, например:

```js
function createEmptyPoint() return { ... };

// constructor
{ point = createEmptyPoint() }
```

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +              <img class="event__photo" src="https://loremflickr.com/248/152?random=${getRandomNumber(1,10)}">
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/view/edit-form-view.js#L116-L119
</details>

Повторю, что нужно использовать только значения из данных, чтобы сейчас, в отсутствие данных с сервера, иметь возможность реализовать логику ТЗ, а потом, при получение данных с сервера к этому месту не возвращаться. Поэтому в случайной генерации ссылок на картинки прямо в шаблоне нет смысла. 

> Случайное изменение картинок в браузере ничего не дает, их отображение уже протестировано верстальщиком, а мы же, как разработки, просто потеряем время и возможность реализации [логики] ТЗ

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1051290164:
> Компоненты `view` должны работать с данными, как с настоящими. Данные (или возможность доступа к ним) следует передавать через аргументы конструктора, как показано в примере демо проекта

Нужно доработать.

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +        <time class="event__date" datetime="${TIME.timeStartInDateTime}">${TIME.date}</time>
По спецификации значение атрибута `datetime` должно быть задано в формате ISO 8601. См. тренажер: [Тег time, дата и время](https://htmlacademy.ru/courses/301/run/15).

```diff
- <time class="event__date" datetime="${TIME.timeStartInDateTime}">${TIME.date}</time>
+ <time class="event__date" datetime="${dateFrom.toISOString()}">${TIME.date}</time>
```

Нужно так же изменить в других местах.

2022-12-21 15:50 UTC, AlexMasterov commented on src/model/points-model.js
> +const TASK_COUNT = 10;
const `TASK`_COUNT = 10;

См. ТЗ.

В нашем проекте нет _задач_, но есть _точки маршрута_.

2022-12-21 15:50 UTC, AlexMasterov commented on src/mock/mock.js
> +const getRandomPoint = () => (getRandomArrayItem(MOCK_POINTS));
const getRandomPoint = () => `(`getRandomArrayItem(MOCK_POINTS)`)`;

`()` избыточны.

2022-12-21 15:50 UTC, AlexMasterov commented on src/main.js
>  const pageBodyContainerElement = pageBody.querySelector('.page-body__container');
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/main.js#L8
</details>

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/main.js#L5-L6
</details>

<details>
<summary>render.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/b80d597870d967f6ed3f42b1d0eaa2669b2c46fd/src/render.js#L9
</details>

Нужно для всего проекта определиться с именованием переменных, которые указывают на DOM-элементы (= объекты типа `Element`) и придерживаться его. Если в одном месте для именования таких переменных используешь суффикс `Element`, то остальные должны тоже его содержать. 

> Если сложно следить за значениям и их типом, то проще не использовать суффикс `Element`

[`Д 6`](https://up.htmlacademy.ru/ecmascript/19/criteries#d6) 
> Используется единый стиль именования переменных

> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, **то это правило работает везде**

2022-12-21 15:50 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +
<details>
<summary>Проблема</summary>

```
edit-form-view.js:68 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at createTemplate (edit-form-view.js:68:152)
```
</details>

Если для вывода формы использовать `EMPTY_POINT`, то возникает ошибка

Нужно разобраться и исправить.

> Из-за этого нельзя нормально протестировать отображение формы в режиме "создания точки маршрута"

[`Б 2`](https://up.htmlacademy.ru/ecmascript/19/criteries#b2) 
> При выполнении кода не возникает необработанных ошибок

2022-12-21 15:51 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      <input id="event-type-${item.type}-${item.offers.id}" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${item.type}" ${item.type.isChecked ? 'checked' : ''}">
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/208946582-0dcc9467-2673-41ca-8470-45a9fe10c305.png)

</details>

Не исправлено.

2022-12-21 15:58 UTC, AlexMasterov commented on src/main.js
> насчет шаблона вроде бы предусмотрела

Не могу нормально проверить из-за ошибки: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054542710.

> про поинт и локалпоинт я не понимаю...

Структуры `Point` и `LocalPoint` отличаются только наличием у `Point` свойства `id`. На этой разнице, на проверки наличия свойства `id`, можно получить удобное для разметки значение, например, `isEditMode` или `isNewMode`. Далее использовать его, чтобы отобразить разницу между режимами формы. 

> Про разницу самих режимов формы см. макет и мои уточнения в замечание: https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1044422469

2022-12-21 16:16 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const timeEndInDateTime = humanizeEventDueDate(dateTo, 'YYYY-MM-DDTHH:mm');
Не реализовано.

Если на защите все же придерутся, вернемся к этому.

2022-12-21 16:19 UTC, AlexMasterov commented on src/view/trip-events-item-view.js
> +  const offersList = () => {
Не реализовано, но это некритично.

2022-12-21 16:21 UTC, AlexMasterov commented on src/util.js
> +function humanizeEventDueDate(dueDate, dateFormat) {
К сожалению, тоже не учтено. `dueDate` есть только в демо проекте.

2022-12-21 16:24 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/208954329-bd07e17f-ec17-484f-aa23-0c59346b095b.png)

</details>

В разметки `undefined`.

Нужно разобраться и исправить.

2022-12-21 16:26 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +      `<section class="event__section  event__section--offers" hidden >
`hidden`

Вместо разметки достаточно пустой одной строки ''.

2022-12-21 16:28 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const destinations = tripDestinations.find((item) => item.id === destination);
const destination`s` = tripDestinations.find((item) => item.id === destination);

Это не массив.

> Про писал в чате ТГ, предлагая вариант. Название исправлено в другом компоненте

2022-12-21 16:31 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +      render(new TripEventsItemView({ point: event, tripDestinations: this.pointsDestinations, tripTypes: this.pointOffersByTypes}), this.tripEventsListView.getElement());
this.`point`sModels.forEach((`event`) => {
`point`: `event`

`point` превращается в `event`.

`trip`Types: this.`pointOffers`ByTypes

Предложения для точек маршрута превращаются в "типы путешествия" 🤔

2022-12-21 16:34 UTC, AlexMasterov commented on src/presenter/main-presenter.js
> +    render(new FilterView, this.tripControlsFilters.getElement());
```diff
- render(new FilterView, this.tripControlsFilters.getElement());
+ render(new FilterView(), this.tripControlsFilters.getElement());
```

2022-12-22 12:46 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  isFavorite: false,
В структуре данных простой версии ТЗ (и твоих моках) нет такого свойства. Оно есть обычной версии, в которой требуется реализовать добавление точек маршрута в избранное.

Нужно удалить:

```diff
- isFavorite: false,
```

2022-12-23 00:05 UTC, AlexMasterov requested changes
Последняя попытка доработать, далее принимаю, как что получится. Уже нужно двигаться дальше.

2022-12-23 00:05 UTC, AlexMasterov commented on src/util.js
> +export {getRandomArrayItem, getRandomNumber, humanizeDate, capitalize};
`getRandomArrayItem`
`getRandomNumber`

Эти функции нужно перенести во _временный_ модуль `mock/mock.js`, чтобы потом не забыть их удалить из _постоянного_ модуля.

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    destination: {
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/3f29ea56923eb93eedfc4aa74a32bbc0ff820cfe/src/view/edit-form-view.js#L9-L15
</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054483695.

В структуре `LocalPoint` значение поля `destination` задано _числом_, что также ожидается сервером. Компоненты в проекте уже _по факту_ ожидают и работают с этой структурой. Поэтому лучше _здесь_ это не менять, а для удобства это следует делать при передаче в `createTemplate`, создав новый объект. (далее подобное покажут в лайве и демо)

<details>
<summary>Вне решения само объявление вызывают вопросы</summary>

`description`: `null`

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054483695:
> Желательно "отсутствие (актуального) значения" задать в рамках одного типа

Для описания (`description`) следовало использовать пустую строку `''`.

`name`: `'kekes'`

Получается, что при создании новой точки маршрута и в отсутствие направления, в качестве названия направления должно отображаться `kekes` и случайная фотка из интернета?

См. ТЗ:
> Пункт назначения. **Выбирается из списка предложенных значений, полученных с сервера. Пользователь не может ввести свой вариант для пункта назначения**

pictures: [{src: https://loremflickr.com/248/152?random=${`getRandomNumber`},

Похоже, что случайная фотка отображаться не будет, поскольку функция `getRandomNumber` используется  без вызова с `()`.

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054589906.
</details>

Объект следует удалить, а в качестве значения `destination` лучше использовать число, например, `0`, или просто `null`, как показано в моем примере (и было написано в чате).

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054544730.

К сожалению, снова не исправлено.

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/208946582-0dcc9467-2673-41ca-8470-45a9fe10c305.png)

</details>

<details>
<summary>Ожидание (markup)</summary>

![image](https://user-images.githubusercontent.com/700213/208219452-2f096bdc-655d-4a25-a98e-a460cfcd8d27.png)

</details>

Нужно, как в макете, выделять (с помощью атрибута `checked`) выбранный тип точки маршрута.

> Это требуется по заданию и ТЗ

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const citiesOptionValueTemplate = tripDestinations.map((item) => `<option value="${item.name}"></option>`).join('');
const `cities`OptionValueTemplate = trip`Destination`s

Названием направления может быть не только город 😃

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/209240624-e757cf2d-39fb-41d8-8b0e-c74d08d3d71c.png)
![image](https://user-images.githubusercontent.com/700213/209240659-f752435c-f1be-46e2-8184-22b03a00d7e2.png)

</details>

При отображение формы с данными от `createEmptyPoint()` в режиме "создания точки маршрута" отображаются `undefined`.

Нужно обработать _отсутствие_ данных о `destination`.

См. снова ТЗ:
> После выбора пункта назначения появляется блок «Destination»

> Если информация о пункте назначения отсутствует, блок «Destination» не отображается

Будет важно для логики:

> Пользователь не может ввести свой вариант для пункта назначения

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/trip-events-list-view.js
> +  return (`<ul class="trip-events__list">
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1047313910.

<details>
<summary>() имеют смысл для форматирования</summary>

```js
function createTemplate() {
  return (
    `<ul class="trip-events__list">
    </ul>`
  );
}
```
</details>

<details>
<summary>() не имеют смысла</summary>

```js
function createTemplate() {
  return `<ul class="trip-events__list"></ul>`;
}

function createTemplate() {
  return `<ul class="trip-events__list">
    </ul>`;
}
```
</details>

2022-12-23 00:05 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    this.pointsModels = this.pointsModel.points;
this.point`s`Model`s` = this.pointsModel.`points`;

Почему список с объектами данных точек маршрута становится моделями (множ. число) 🤔

this.pointsModels = this.pointsModel.`points`;

Для получение данных из модели есть метод:

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/3f29ea56923eb93eedfc4aa74a32bbc0ff820cfe/src/model/points-model.js#L10-L11

Нужно исправить:
```diff
-  this.pointsModels = this.pointsModel.points;
+  this.points = this.pointsModel.getPoints();
```

Желательно так же исправить в похожим местах ниже.

2022-12-23 00:05 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +      render(new TripEventsItemView({ point: points, tripDestinations: this.pointsDestinations, mockOffers: this.pointOffersByTypes}), this.tripEventsListView.getElement());
`mock`Offers: this.pointOffersByTypes

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1051290164:
> Компоненты `view` должны работать с данными, **как с настоящими**

Не понимаю, почему во всем проекте для свойств с данными появилась нагрузка `mock`. Зачем и что будет, когда будет работать с (реальными) данными с сервера, которые уже не будут "моковыми" 🤔

> О подобных изменениях следует советоваться

Нужно исправить _всем проекте_, убрав из названий свойств `mock`, например, упростив до `offers`, `allOffers`, `offersByTypes`.

2022-12-23 00:05 UTC, AlexMasterov commented on src/presenter/main-presenter.js
> +  tripControlsFilters = new TripControlsFiltersView();
Желательно уже определиться с именованием компонентов-представления:
```diff
- tripControlsFilters = new TripControlsFiltersView();
+ tripControlsFiltersView = new TripControlsFiltersView();
```

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const picturesforTemplate = picture.pictures;
Это:
```js
const picture = tripDestinations.find((pictures) => pictures === pictures);
const picturesforTemplate = picture.pictures;
```
Тоже самое, что:
```js
tripDestinations[0].pictures;
```
Таким образом всегда выбираются изображения первого направления в списке, что странно по реализации и неправильно по ТЗ.

Нужно использовать список изображений из данных _выбранного_ направления, `destinationInfo.pictures`.

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +<div class="event__photos-container">
Таким образом в разметку добавляется пустая строка (= символ перевода строки `\n`).

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1047313910:
> Так же важно помнить, что шаблонный строки сохраняют пробелы и переводы строки. На основе разметки с пустой строкой в начале будет создан узел типа `#text` (а не `Element`), который нам не нужен. **Желательно этого не допускать**

В этом случае будет просто лишняя пустая строка, но желательно и этого не допускать, используя `()` для форматирования с переводом строки.

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +picturesforTemplate.map((pic) => `
picturesforTemplate.map((`pic`) => `

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054457172

[`Б 4`](https://up.htmlacademy.ru/ecmascript/19/criteries#b4)
> Сокращения в словах запрещены

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +picturesforTemplate.map((pic) => `
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/3f29ea56923eb93eedfc4aa74a32bbc0ff820cfe/src/view/edit-form-view.js#L30-L40
</details>

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/209244971-3270a344-0afc-4bfe-88de-4a36cb958650.png)
![image](https://user-images.githubusercontent.com/700213/209245808-8e5b726f-e5a8-4b13-8cb4-4e861e083e47.png)
</details>

Узел с контейнером `event__photos-container` дублируется по кол. изображений, добавляя скроллы, а вместо изображений из данных направления отображаются _фикс. количество_ фото со случайными котами. Изображений всегда `5`, даже если столько нет в списке. Таким образом будут новые `undefined` вместо изображений.

Повторю, что нужно использовать значения из данных, без подмены и в том же количестве.

2022-12-23 00:05 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +              <img class="event__photo" src="${pic.src}" alt="Event photo">
\<img class="event__photo" src="${pic.src}" alt="`Event photo`"\>

Для описания изображения нужно использовать значение из данных.

2022-12-23 15:38 UTC, AlexMasterov commented on src/presenter/main-presenter.js
> +  TripControlsFiltersView = new TripControlsFiltersView();
`T`ripControlsFiltersView = new TripControlsFiltersView();

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1053289027

> См. мой пример https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1055935265

[`Б 3`](https://up.htmlacademy.ru/ecmascript/19/criteries#b3) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации [`camelCase`](https://ru.wikipedia.org/wiki/CamelCase)

2022-12-23 15:38 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +picturesforTemplate?.map((photos = destinationInfo) => (
🤔

2022-12-23 15:38 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const picturesforTemplate = picture.pictures;
Не исправленою

2022-12-23 15:38 UTC, AlexMasterov commented on src/view/edit-form-view.js
Не исправлено.

2022-12-23 15:39 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +picturesforTemplate.map((pic) => `
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/209361609-10a9fd8c-675c-4edd-8a2b-e8bc1ff13b8c.png)

</details>

Не исправлено.

2022-12-23 15:39 UTC, AlexMasterov approved these changes

2022-12-23 15:41 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const picturesforTemplate = picture.pictures;
Должным образом не исправлено.

2022-12-23 15:42 UTC, merged

2022-12-23 15:42 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    this.points.forEach((points) => {
```diff
- this.points.forEach((points) => {
+ this.points.forEach((point) => {
```

2022-12-23 15:44 UTC, AlexMasterov commented on src/util.js
> +export {getRandomArrayItem, getRandomNumber, humanizeDate, capitalize};
После переноса этих функций, их нужно удалить из этого модуля. В этом был смысл.

2022-12-23 15:45 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const picturesforTemplate = destinationInfo?.pictures;
```js
Array.isArray(picturesforTemplate) // true
```
[`Б 8`](https://up.htmlacademy.ru/ecmascript/19/criteries#b8) 
> Массивы названы существительными во множественном числе

2022-12-23 15:47 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +              <img class="event__photo" src="${photos.src}" alt="${photos.description}">
picturesforTemplate?.map((`photos = destinationInfo`) => (

Странный код.

\<img class="event__photo" src="${photo`s`.src}" alt="${photo`s`.description}"\>

Снова объект назван в множ. числе.

2022-12-23 15:49 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    ${destinationInfo?.description.length > 1 ?
`length > 1`

Нужна проверка на пустоту строки, т.е. `.length > 0` или `=== ''`, `!==  ''`.

2022-12-23 16:12 UTC, AlexMasterov commented
Пожалуйста, мелкие замечания в остатке постарайся учесть при выполнении следующего задания.

2022-12-23 16:27 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/209367709-9f84fa97-e02b-4131-89b7-6b65722e35ec.png)

</details>

У формы в режиме "создания точки маршрута" пропало поле ввода/выбора направления.

2022-12-23 16:29 UTC, AlexMasterov commented on src/view/edit-form-view.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/209367843-e0c20e91-519c-4e5d-88a9-ee359640e78d.png)

</details>

<details>
<summary>Ожидание (markup)</summary>

![image](https://user-images.githubusercontent.com/700213/209367896-414e53f1-1a5a-4d9c-93f4-2441b2263d55.png)

</details>

Форма с данными от `createEmptyPoint()` в режиме "создания точки маршрута" отображается, как в режиме редактирования.

2022-12-23 16:32 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  const tripOffers = offerByType.offers;
```diff
- const tripOffers = offerByType.offers;
+ const typeOffers = offerByType.offers;
```

2022-12-23 16:35 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +    destinationInfo?.name.length > 1 ?
`.length > 1`

См. похожие замечание.

2022-12-23 17:10 UTC, Domish4 commented on src/view/edit-form-view.js
> +    destinationInfo?.name.length > 1 ?
Спасибо большое, я обязательно постараюсь все учесть, знаю что делаю глупые ошибки, причем каждый раз все просматриваю перед отправкой.... может за неделю совсем мозг расплылся. в общем постепенно я все починю, сейчас бы хотелось отправляться дальше по разделам а не стоять на месте... Спасибо за помощь)

2022-12-28 09:40 UTC, Domish4 commented on src/view/edit-form-view.js
> +picturesforTemplate.map((pic) => `
Я не совсем понимаю, значения из данных имеются ввиду src="img/photos/1.jpg"? как изначально в разметке было? 
или как в структурах данных написано  "src": "http://picsum.photos/300/200?r=0.0762563005163317",? просто в задании написано что можно брать рандомные фото с котами. но может ты вообще о другом сейчас и я просто не понимаю...