Революция или эволюция + мелкие правки по прошлому заданию
htmlacademy-ecmascript/2073335-big-trip-simple-19 pull request #5
Opened 2022-12-29 08:07 UTC by Domish4

2022-12-29 18:04 UTC, AlexMasterov requested changes

2022-12-29 18:04 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +      if (evt.key === 'Escape' || evt.key === 'Esc') {
См. [String.p.`startsWith`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith):

```diff
- if (evt.key === 'Escape' || evt.key === 'Esc') {
+ if (evt.key.startsWith('Esc')) {
```

> `.startsWith` был оптимизирован в движке V8

<details>
<summary>Еще пример, но многословней</summary>

```js
const ESCAPE_KEYS = ['Escape', 'Esc'];

function isEscapeKey(evt) {
  return ESCAPE_KEYS.includes(evt.key);
};
```

```diff
- if (evt.key === 'Escape' || evt.key === 'Esc') {
+ if (isEscapeKey(evt.key)) {
```
</details>

2022-12-29 18:04 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +      this.#renderItem(this.#points[i], this.#pointsDestinations, this.#pointsOffersByTypes);
В цикле `for` значение инкремента `i` используется только для обращение к массиву `this.points`.

Нужно переписать цикл `for` на `for of` (или `.forEach`, как было раньше).

[Д20](https://up.htmlacademy.ru/ecmascript/19/criteries#d20)
>  Там, где не требуется индекс элемента массива или нужно обойти все элементы итерируемой структуры данных, используется цикл `for .. of` вместо цикла `for`

[Д24](https://up.htmlacademy.ru/ecmascript/19/criteries#d24) 
> Для работы с JS-коллекциями используются итераторы для массивов

2022-12-29 18:04 UTC, AlexMasterov commented on src/view/trip-events-view.js
>  export default class TripEventsView{
Форматирование:
```diff
- export default class TripEventsView{
+ export default class TripEventsView {
```

2022-12-29 18:04 UTC, AlexMasterov commented on src/view/trip-main-view.js
>  export default class TripMainView{
```diff
- export default class TripMainView{
+ export default class TripMainView {
```

2022-12-29 18:04 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +  #renderItem(point) {
```diff
- #renderItem(point) {
+ #renderPoint(point) {
```

2022-12-29 18:04 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  return '<button class="event__reset-btn" type="reset">Cancel</button>';
Обычно с `is` называют [функции-предикаты](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B5%D0%B4%D0%B8%D0%BA%D0%B0%D1%82), которые возвращают _булево_ значение:

<details>
<summary>JS1-Б4</summary>

![image](https://user-images.githubusercontent.com/700213/209985881-6c915d4a-e3f8-41ae-94fc-d35e41b9909b.png)

</details>

Но здесь функция создает и возвращает _строкой_ шаблон с разметкой и это совсем не выражено в её название.

Нужно назвать в формате `create*Template`, как уже были названы подобные функции. Такое название должно помогать понять, какая именно создается разметка, а не для чего.

[Б10](https://up.htmlacademy.ru/ecmascript/19/criteries#b10)
> Название функции или метода должно быть глаголом и **соответствовать действию**, которое выполняет функция или метод

2022-12-29 18:04 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  return `<button class="event__reset-btn" type="reset">Delete</button>
<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L16
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L20
</details>

Разметка отличается только названием кнопки.

2022-12-29 18:04 UTC, AlexMasterov commented on src/view/edit-form-view.js
>    const destinationInfo = tripDestinations.find((item) => item.id === destination);
<details>
<summary>Проблема</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L32
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L34-L35
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L84
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L124
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L127
</details>

destinationInfo`?.`name === undefined

Оператор `?.` _уже_ проверяет, что в объекте есть свойство `destinationInfo.name`. (он был отчасти добавлен в язык для подобного случая) Поэтому следом за ним проверка на `undefined` вернет `false`.

> Исключением может быть наличие свойства, но с явно заданными значением `undefined`: `{ name: undefined }`. Надеюсь, что это не наш случай, иначе всё плохо~

Д13, ~Д16

<details>
<summary>hint</summary>

См. Оператор нулевого слияния [`??`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing).

<details>
<summary>Пример ?. + ??</summary>

Это:
```js
destinationInfo?.name === undefined ? '' : destinationInfo?.name
```
Тоже самое (по результату):
```js
destinationInfo?.name ?? ''
```
</details>

Много destinationInfo`?.`.

<details>
<summary>Пример решения без .?</summary>

```js
const BLANK_DESTINATION = {
  name: '',
  description: '',
  pictures: [],
};

// createTemplate
const {
  name: destinationName,
  description,
  pictures,
} = tripDestinations.find(({ id }) => id === destination) ?? BLANK_DESTINATION;
```
</details>


</details>

2022-12-29 18:04 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +templatePictures?.map((photo = destinationInfo) => (
См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1056433307:
> Странный код

<details>
<summary>view/edit-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L29
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L32
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/edit-form-view.js#L34-L35
</details>

templatePictures?.map((photo `= destinationInfo`) => (

`destinationInfo` это объект с _данными направления_ и у него нет поля `src` и `description`. Такие поля есть только у объекта с _данными изображения_, который можно получить из списка `destinationInfo.pictures`.

1. `templatePictures` указывает на список с объектами изображений `destinationInfo.pictures`, т.е. здесь в качестве значения по умолчанию вместо структуры _объекта изображения_ используется _объект направления_;
2. Установка значения по умолчанию `= destinationInfo` сработает только в случае, если параметр `photo` указывает на `undefined`. Но для этого в случае итерации Array.p.`map` элементы списка должны сами _явно_ указывать на `undefined`, а при отсутствие элементов или дырок в списке, они будут пропущены при итерации;
3. В случае пустого массива `templatePictures`  (= отсутствие элементов или дырок в нем) `.map` вообще не запустит итерацию.

Нужно удалить `= destinationInfo`.

Д8, Д9

2022-12-29 18:09 UTC, AlexMasterov commented on src/presenter/board-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/209992290-0bacbe28-bd68-4626-9993-10195f03756b.png)

</details>

См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1056427085.

Не исправлено.

2022-12-29 18:12 UTC, AlexMasterov commented on src/presenter/board-presenter.js
>  export default class BoardPresenter {
class `Board`Presenter {

В ТЗ нашего проекта нет _доски_, а есть _список_ 😃

> См. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/4#discussion_r1054526903

2022-12-29 18:15 UTC, AlexMasterov commented on src/presenter/board-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/209992793-44ffe5fc-94db-4d83-93f2-f9aa01e92f95.png)
</details>

Если развернуть и свернуть точку маршрута, при нажатие на `Esc` выбрасывается исключение (ошибка).

Нужно разобраться и исправить.

Б2, Б26

2022-12-29 20:35 UTC, AlexMasterov commented on src/presenter/main-presenter.js
<details>
<summary>view/filter-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/filter-view.js#L6-L9
https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/687134f2d4068b42c0802cbc1a8a14a47f8ab745/src/view/filter-view.js#L11-L14
</details>

Разметка с фильтрами почти полностью дублируется, отличаясь только значениями некоторых атрибутов.

Попробуй для создания одной разметки `.trip-filters__filter` написать функцию, например, с таким интерфейсом:

```js
createFilterTemplate({ id: 'everything', name: 'Everything', isChecked: true })
createFilterTemplate({ id: 'future', name: 'Future' })
```
> Нам это поможет далее при реализации фильтрации

2022-12-29 21:09 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    const replaceCardToForm = () => {
const replace`Card`ToForm = () => {

В ТЗ нет карточек 😃

2022-12-29 21:13 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    const editFormView = new EditFormView({point, tripDestinations: this.#pointsDestinations, allOffers: this.#pointsOffersByTypes});
`TripEventsItemView`
`EditFormView`

Попробуй упростить название, например, можно назвать `PointCardView` и `PointFormView` или похожим образом.

2022-12-30 10:17 UTC, Domish4 commented on src/presenter/board-presenter.js
проблема в том, что они как бы вертикально? а не горизонтально? просто у меня все ок... и разметка одинаковая с макетом и вот это вот все

2022-12-30 11:07 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> проблема в том, что они как бы вертикально? а не горизонтально?

Да. Проблема с разметкой:

> Узел с контейнером `.event__photos-container` дублируется по кол. изображений

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/210063550-987147aa-18f5-4c2e-87f9-baa097966c4b.png)

</details>

<details>
<summary>Ожидание (markup)</summary>

![image](https://user-images.githubusercontent.com/700213/210063488-62fb9ea8-0d12-42c6-ac01-97bb0ace89ac.png)

![image](https://user-images.githubusercontent.com/700213/210063585-45ef7e58-541a-4a7c-9914-a7788fcb0ebe.png)

</details>

2023-01-04 15:48 UTC, Domish4 commented on src/presenter/main-presenter.js
Сделаю ближе к тому моменту когда будет реализация фильтрации

2023-01-04 16:07 UTC, Domish4 commented on src/view/edit-form-view.js
> +  return `<button class="event__reset-btn" type="reset">Delete</button>
Это плохо? нужно как-то по другому сделать?...

2023-01-04 16:39 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +    for (const points of this.#points) {
```diff
- for (const points of this.#points) {
+ for (const point of this.#points) {
```

2023-01-04 16:39 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      if (evt.key.startsWith('Esc') || pointFormView.element.querySelector('.event__rollup-btn') ) {
`|| pointFormView.element.querySelector('.event__rollup-btn')`

Нужно удалить.

2023-01-04 16:39 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +function getButtonCancelTemplate() {
```diff
- function getButtonCancelTemplate() {
+ function createButtonCancelTemplate() {
```

2023-01-04 16:39 UTC, AlexMasterov commented on src/main.js
>  const pageBodyContainerElement = pageBodyElement.querySelector('.page-body__container');
Пожалуйста, добавь пустую строку.

2023-01-04 16:39 UTC, merged

2023-01-05 15:21 UTC, AlexMasterov commented on src/view/edit-form-view.js
> +  return `<button class="event__reset-btn" type="reset">Delete</button>
Вариантов текста может быть больше, а так же их перевод на разные языки. В таком случае на каждый вариант будет целиком дублироваться разметка, хотя она не меняется. 

Подобное уже происходит с целым компонентом, см. https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/pull/3#discussion_r1046127671:

> Вместо того, чтобы создавать отдельные компоненты под каждое сообщение, можно реализовать один универсальный, например, `TripMessageView`, который мог бы принимать в качестве аргумент любое сообщение

<details>
<summary>Примеры</summary>

```js
new TripMessageView(TripMessageText.NO_POINTS)
```
```js
const resetButtonText = isNew
  ? ResetButtonText.CANCEL
  : ResetButtonText.DELETE;

// ...
<button class="event__reset-btn" type="reset">${resetButtonText}</button>
```
```js
function createResetButtonTemplate(text) {
  return (
    `<button class="event__reset-btn" type="reset">${text}</button>`
  )
}

// ...
createResetButtonTemplate(ResetButtonText.CANCEL)
createResetButtonTemplate(ResetButtonText.DELETE)
```
</details>